#ifndef GLO_EGL_H_
#define GLO_EGL_H_


#define GLO_EGL
#define GLO_OPTION_EGL_LOADER

#ifdef __cplusplus
extern "C" {
#endif

#ifndef GLO_PLATFORM_H_
#define GLO_PLATFORM_H_

#ifndef GLO_PLATFORM_WIN32
  #if defined(_WIN32) || defined(__WIN32__) || defined(WIN32) || defined(__MINGW32__)
    #define GLO_PLATFORM_WIN32 1
  #else
    #define GLO_PLATFORM_WIN32 0
  #endif
#endif

#ifndef GLO_PLATFORM_APPLE
  #ifdef __APPLE__
    #define GLO_PLATFORM_APPLE 1
  #else
    #define GLO_PLATFORM_APPLE 0
  #endif
#endif

#ifndef GLO_PLATFORM_EMSCRIPTEN
  #ifdef __EMSCRIPTEN__
    #define GLO_PLATFORM_EMSCRIPTEN 1
  #else
    #define GLO_PLATFORM_EMSCRIPTEN 0
  #endif
#endif

#ifndef GLO_PLATFORM_UWP
  #if defined(_MSC_VER) && !defined(GLO_INTERNAL_HAVE_WINAPIFAMILY)
    #ifdef __has_include
      #if __has_include(<winapifamily.h>)
        #define GLO_INTERNAL_HAVE_WINAPIFAMILY 1
      #endif
    #elif _MSC_VER >= 1700 && !_USING_V110_SDK71_
      #define GLO_INTERNAL_HAVE_WINAPIFAMILY 1
    #endif
  #endif

  #ifdef GLO_INTERNAL_HAVE_WINAPIFAMILY
    #include <winapifamily.h>
    #if !WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
      #define GLO_PLATFORM_UWP 1
    #endif
  #endif

  #ifndef GLO_PLATFORM_UWP
    #define GLO_PLATFORM_UWP 0
  #endif
#endif

#ifdef __GNUC__
  #define GLO_GNUC_EXTENSION __extension__
#else
  #define GLO_GNUC_EXTENSION
#endif

#define GLO_UNUSED(x) (void)(x)

#ifndef GLO_API_CALL
  #if defined(GLO_API_CALL_EXPORT)
    #if GLO_PLATFORM_WIN32 || defined(__CYGWIN__)
      #if defined(GLO_API_CALL_EXPORT_BUILD)
        #if defined(__GNUC__)
          #define GLO_API_CALL __attribute__ ((dllexport)) extern
        #else
          #define GLO_API_CALL __declspec(dllexport) extern
        #endif
      #else
        #if defined(__GNUC__)
          #define GLO_API_CALL __attribute__ ((dllimport)) extern
        #else
          #define GLO_API_CALL __declspec(dllimport) extern
        #endif
      #endif
    #elif defined(__GNUC__) && defined(GLO_API_CALL_EXPORT_BUILD)
      #define GLO_API_CALL __attribute__ ((visibility ("default"))) extern
    #else
      #define GLO_API_CALL extern
    #endif
  #else
    #define GLO_API_CALL extern
  #endif
#endif

#ifdef APIENTRY
  #define GLO_API_PTR APIENTRY
#elif GLO_PLATFORM_WIN32
  #define GLO_API_PTR __stdcall
#else
  #define GLO_API_PTR
#endif

#ifndef GLAPI
#define GLAPI GLO_API_CALL
#endif

#ifndef GLAPIENTRY
#define GLAPIENTRY GLO_API_PTR
#endif

#define GLO_MAKE_VERSION(major, minor) (major * 10000 + minor)
#define GLO_VERSION_MAJOR(version) (version / 10000)
#define GLO_VERSION_MINOR(version) (version % 10000)

#define GLO_GENERATOR_VERSION "2.0.8"

typedef void (*GLOapiproc)(void);

typedef GLOapiproc (*GLOloadfunc)(const char *name);
typedef GLOapiproc (*GLOuserptrloadfunc)(void *userptr, const char *name);

typedef void (*GLOprecallback)(const char *name, GLOapiproc apiproc, int len_args, ...);
typedef void (*GLOpostcallback)(void *ret, const char *name, GLOapiproc apiproc, int len_args, ...);

#endif /* GLO_PLATFORM_H_ */

#define EGL_ALLOC_NEW_DISPLAY_EXT 0x3379
#define EGL_ALPHA_FORMAT 0x3088
#define EGL_ALPHA_FORMAT_NONPRE 0x308B
#define EGL_ALPHA_FORMAT_PRE 0x308C
#define EGL_ALPHA_MASK_SIZE 0x303E
#define EGL_ALPHA_SIZE 0x3021
#define EGL_ALREADY_SIGNALED_NV 0x30EA
#define EGL_AUTO_STEREO_NV 0x3136
#define EGL_BACK_BUFFER 0x3084
#define EGL_BAD_ACCESS 0x3002
#define EGL_BAD_ALLOC 0x3003
#define EGL_BAD_ATTRIBUTE 0x3004
#define EGL_BAD_CONFIG 0x3005
#define EGL_BAD_CONTEXT 0x3006
#define EGL_BAD_CURRENT_SURFACE 0x3007
#define EGL_BAD_DEVICE_EXT 0x322B
#define EGL_BAD_DISPLAY 0x3008
#define EGL_BAD_MATCH 0x3009
#define EGL_BAD_NATIVE_PIXMAP 0x300A
#define EGL_BAD_NATIVE_WINDOW 0x300B
#define EGL_BAD_OUTPUT_LAYER_EXT 0x322D
#define EGL_BAD_OUTPUT_PORT_EXT 0x322E
#define EGL_BAD_PARAMETER 0x300C
#define EGL_BAD_STATE_KHR 0x321C
#define EGL_BAD_STREAM_KHR 0x321B
#define EGL_BAD_SURFACE 0x300D
#define EGL_BIND_TO_TEXTURE_RGB 0x3039
#define EGL_BIND_TO_TEXTURE_RGBA 0x303A
#define EGL_BITMAP_ORIGIN_KHR 0x30C8
#define EGL_BITMAP_PITCH_KHR 0x30C7
#define EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR 0x30CC
#define EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR 0x30CB
#define EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR 0x30CA
#define EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR 0x30CD
#define EGL_BITMAP_PIXEL_RED_OFFSET_KHR 0x30C9
#define EGL_BITMAP_PIXEL_SIZE_KHR 0x3110
#define EGL_BITMAP_POINTER_KHR 0x30C6
#define EGL_BLUE_SIZE 0x3022
#define EGL_BOTTOM_NV 0x336E
#define EGL_BUFFER_AGE_EXT 0x313D
#define EGL_BUFFER_AGE_KHR 0x313D
#define EGL_BUFFER_DESTROYED 0x3095
#define EGL_BUFFER_PRESERVED 0x3094
#define EGL_BUFFER_SIZE 0x3020
#define EGL_CLIENT_APIS 0x308D
#define EGL_CLIENT_PIXMAP_POINTER_HI 0x8F74
#define EGL_CL_EVENT_HANDLE 0x309C
#define EGL_CL_EVENT_HANDLE_KHR 0x309C
#define EGL_COLORSPACE 0x3087
#define EGL_COLORSPACE_LINEAR 0x308A
#define EGL_COLORSPACE_sRGB 0x3089
#define EGL_COLOR_ARGB_HI 0x8F73
#define EGL_COLOR_BUFFER_TYPE 0x303F
#define EGL_COLOR_COMPONENT_TYPE_EXT 0x3339
#define EGL_COLOR_COMPONENT_TYPE_FIXED_EXT 0x333A
#define EGL_COLOR_COMPONENT_TYPE_FLOAT_EXT 0x333B
#define EGL_COLOR_COMPONENT_TYPE_INTEGER_ARM 0x3288
#define EGL_COLOR_COMPONENT_TYPE_UNSIGNED_INTEGER_ARM 0x3287
#define EGL_COLOR_FORMAT_HI 0x8F70
#define EGL_COLOR_RGBA_HI 0x8F72
#define EGL_COLOR_RGB_HI 0x8F71
#define EGL_COMPOSITE_DEADLINE_ANDROID 0x3431
#define EGL_COMPOSITE_INTERVAL_ANDROID 0x3432
#define EGL_COMPOSITE_TO_PRESENT_LATENCY_ANDROID 0x3433
#define EGL_COMPOSITION_LATCH_TIME_ANDROID 0x3436
#define EGL_COMPOSITOR_DROP_NEWEST_FRAME_EXT 0x3462
#define EGL_COMPOSITOR_KEEP_NEWEST_FRAME_EXT 0x3463
#define EGL_CONDITION_SATISFIED 0x30F6
#define EGL_CONDITION_SATISFIED_KHR 0x30F6
#define EGL_CONDITION_SATISFIED_NV 0x30EC
#define EGL_CONFIG_CAVEAT 0x3027
#define EGL_CONFIG_ID 0x3028
#define EGL_CONFIG_SELECT_GROUP_EXT 0x34C0
#define EGL_CONFORMANT 0x3042
#define EGL_CONFORMANT_KHR 0x3042
#define EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR 0x321E
#define EGL_CONSUMER_AUTO_ORIENTATION_NV 0x3369
#define EGL_CONSUMER_FRAME_KHR 0x3213
#define EGL_CONSUMER_LATENCY_USEC_KHR 0x3210
#define EGL_CONSUMER_MAX_FRAME_HINT_NV 0x3338
#define EGL_CONSUMER_METADATA_NV 0x3254
#define EGL_CONTEXT_CLIENT_TYPE 0x3097
#define EGL_CONTEXT_CLIENT_VERSION 0x3098
#define EGL_CONTEXT_FLAGS_KHR 0x30FC
#define EGL_CONTEXT_LOST 0x300E
#define EGL_CONTEXT_MAJOR_VERSION 0x3098
#define EGL_CONTEXT_MAJOR_VERSION_KHR 0x3098
#define EGL_CONTEXT_MINOR_VERSION 0x30FB
#define EGL_CONTEXT_MINOR_VERSION_KHR 0x30FB
#define EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT 0x00000002
#define EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR 0x00000002
#define EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT 0x00000001
#define EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR 0x00000001
#define EGL_CONTEXT_OPENGL_DEBUG 0x31B0
#define EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR 0x00000001
#define EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE 0x31B1
#define EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR 0x00000002
#define EGL_CONTEXT_OPENGL_NO_ERROR_KHR 0x31B3
#define EGL_CONTEXT_OPENGL_PROFILE_MASK 0x30FD
#define EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR 0x30FD
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY 0x31BD
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT 0x3138
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR 0x31BD
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS 0x31B2
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR 0x00000004
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT 0x30BF
#define EGL_CONTEXT_PRIORITY_HIGH_IMG 0x3101
#define EGL_CONTEXT_PRIORITY_LEVEL_IMG 0x3100
#define EGL_CONTEXT_PRIORITY_LOW_IMG 0x3103
#define EGL_CONTEXT_PRIORITY_MEDIUM_IMG 0x3102
#define EGL_CONTEXT_PRIORITY_REALTIME_NV 0x3357
#define EGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_KHR 0x2098
#define EGL_CONTEXT_RELEASE_BEHAVIOR_KHR 0x2097
#define EGL_CONTEXT_RELEASE_BEHAVIOR_NONE_KHR 0
#define EGL_CORE_NATIVE_ENGINE 0x305B
#define EGL_COVERAGE_BUFFERS_NV 0x30E0
#define EGL_COVERAGE_SAMPLES_NV 0x30E1
#define EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV 0x3132
#define EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV 0x3133
#define EGL_COVERAGE_SAMPLE_RESOLVE_NV 0x3131
#define EGL_CTA861_3_MAX_CONTENT_LIGHT_LEVEL_EXT 0x3360
#define EGL_CTA861_3_MAX_FRAME_AVERAGE_LEVEL_EXT 0x3361
#define EGL_CUDA_DEVICE_NV 0x323A
#define EGL_CUDA_EVENT_HANDLE_NV 0x323B
#define EGL_D3D11_DEVICE_ANGLE 0x33A1
#define EGL_D3D9_DEVICE_ANGLE 0x33A0
#define EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE 0x3200
#define EGL_DEBUG_CALLBACK_KHR 0x33B8
#define EGL_DEBUG_MSG_CRITICAL_KHR 0x33B9
#define EGL_DEBUG_MSG_ERROR_KHR 0x33BA
#define EGL_DEBUG_MSG_INFO_KHR 0x33BC
#define EGL_DEBUG_MSG_WARN_KHR 0x33BB
#define EGL_DEFAULT_DISPLAY EGL_CAST(EGLNativeDisplayType,0)
#define EGL_DEPTH_ENCODING_NONE_NV 0
#define EGL_DEPTH_ENCODING_NONLINEAR_NV 0x30E3
#define EGL_DEPTH_ENCODING_NV 0x30E2
#define EGL_DEPTH_SIZE 0x3025
#define EGL_DEQUEUE_READY_TIME_ANDROID 0x343B
#define EGL_DEVICE_EXT 0x322C
#define EGL_DEVICE_UUID_EXT 0x335C
#define EGL_DISCARD_SAMPLES_ARM 0x3286
#define EGL_DISPLAY_PRESENT_TIME_ANDROID 0x343A
#define EGL_DISPLAY_SCALING 10000
#define EGL_DMA_BUF_PLANE0_FD_EXT 0x3272
#define EGL_DMA_BUF_PLANE0_MODIFIER_HI_EXT 0x3444
#define EGL_DMA_BUF_PLANE0_MODIFIER_LO_EXT 0x3443
#define EGL_DMA_BUF_PLANE0_OFFSET_EXT 0x3273
#define EGL_DMA_BUF_PLANE0_PITCH_EXT 0x3274
#define EGL_DMA_BUF_PLANE1_FD_EXT 0x3275
#define EGL_DMA_BUF_PLANE1_MODIFIER_HI_EXT 0x3446
#define EGL_DMA_BUF_PLANE1_MODIFIER_LO_EXT 0x3445
#define EGL_DMA_BUF_PLANE1_OFFSET_EXT 0x3276
#define EGL_DMA_BUF_PLANE1_PITCH_EXT 0x3277
#define EGL_DMA_BUF_PLANE2_FD_EXT 0x3278
#define EGL_DMA_BUF_PLANE2_MODIFIER_HI_EXT 0x3448
#define EGL_DMA_BUF_PLANE2_MODIFIER_LO_EXT 0x3447
#define EGL_DMA_BUF_PLANE2_OFFSET_EXT 0x3279
#define EGL_DMA_BUF_PLANE2_PITCH_EXT 0x327A
#define EGL_DMA_BUF_PLANE3_FD_EXT 0x3440
#define EGL_DMA_BUF_PLANE3_MODIFIER_HI_EXT 0x344A
#define EGL_DMA_BUF_PLANE3_MODIFIER_LO_EXT 0x3449
#define EGL_DMA_BUF_PLANE3_OFFSET_EXT 0x3441
#define EGL_DMA_BUF_PLANE3_PITCH_EXT 0x3442
#define EGL_DONT_CARE EGL_CAST(EGLint,-1)
#define EGL_DRAW 0x3059
#define EGL_DRIVER_NAME_EXT 0x335E
#define EGL_DRIVER_UUID_EXT 0x335D
#define EGL_DRM_BUFFER_FORMAT_ARGB32_MESA 0x31D2
#define EGL_DRM_BUFFER_FORMAT_MESA 0x31D0
#define EGL_DRM_BUFFER_MESA 0x31D3
#define EGL_DRM_BUFFER_STRIDE_MESA 0x31D4
#define EGL_DRM_BUFFER_USE_CURSOR_MESA 0x00000004
#define EGL_DRM_BUFFER_USE_MESA 0x31D1
#define EGL_DRM_BUFFER_USE_SCANOUT_MESA 0x00000001
#define EGL_DRM_BUFFER_USE_SHARE_MESA 0x00000002
#define EGL_DRM_CONNECTOR_EXT 0x3236
#define EGL_DRM_CRTC_EXT 0x3234
#define EGL_DRM_DEVICE_FILE_EXT 0x3233
#define EGL_DRM_MASTER_FD_EXT 0x333C
#define EGL_DRM_PLANE_EXT 0x3235
#define EGL_DRM_RENDER_NODE_FILE_EXT 0x3377
#define EGL_EXTENSIONS 0x3055
#define EGL_EXTERNAL_REF_ID_EXT 0x3461
#define EGL_FALSE 0
#define EGL_FIRST_COMPOSITION_GPU_FINISHED_TIME_ANDROID 0x3439
#define EGL_FIRST_COMPOSITION_START_TIME_ANDROID 0x3437
#define EGL_FIXED_SIZE_ANGLE 0x3201
#define EGL_FOREVER 0xFFFFFFFFFFFFFFFF
#define EGL_FOREVER_KHR 0xFFFFFFFFFFFFFFFF
#define EGL_FOREVER_NV 0xFFFFFFFFFFFFFFFF
#define EGL_FORMAT_RGBA_8888_EXACT_KHR 0x30C2
#define EGL_FORMAT_RGBA_8888_KHR 0x30C3
#define EGL_FORMAT_RGB_565_EXACT_KHR 0x30C0
#define EGL_FORMAT_RGB_565_KHR 0x30C1
#define EGL_FRAMEBUFFER_TARGET_ANDROID 0x3147
#define EGL_FRONT_BUFFER_AUTO_REFRESH_ANDROID 0x314C
#define EGL_FRONT_BUFFER_EXT 0x3464
#define EGL_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV 0x334C
#define EGL_GL_COLORSPACE 0x309D
#define EGL_GL_COLORSPACE_BT2020_HLG_EXT 0x3540
#define EGL_GL_COLORSPACE_BT2020_LINEAR_EXT 0x333F
#define EGL_GL_COLORSPACE_BT2020_PQ_EXT 0x3340
#define EGL_GL_COLORSPACE_DEFAULT_EXT 0x314D
#define EGL_GL_COLORSPACE_DISPLAY_P3_EXT 0x3363
#define EGL_GL_COLORSPACE_DISPLAY_P3_LINEAR_EXT 0x3362
#define EGL_GL_COLORSPACE_DISPLAY_P3_PASSTHROUGH_EXT 0x3490
#define EGL_GL_COLORSPACE_KHR 0x309D
#define EGL_GL_COLORSPACE_LINEAR 0x308A
#define EGL_GL_COLORSPACE_LINEAR_KHR 0x308A
#define EGL_GL_COLORSPACE_SCRGB_EXT 0x3351
#define EGL_GL_COLORSPACE_SCRGB_LINEAR_EXT 0x3350
#define EGL_GL_COLORSPACE_SRGB 0x3089
#define EGL_GL_COLORSPACE_SRGB_KHR 0x3089
#define EGL_GL_RENDERBUFFER 0x30B9
#define EGL_GL_RENDERBUFFER_KHR 0x30B9
#define EGL_GL_TEXTURE_2D 0x30B1
#define EGL_GL_TEXTURE_2D_KHR 0x30B1
#define EGL_GL_TEXTURE_3D 0x30B2
#define EGL_GL_TEXTURE_3D_KHR 0x30B2
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X 0x30B4
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR 0x30B4
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 0x30B6
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR 0x30B6
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 0x30B8
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR 0x30B8
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X 0x30B3
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR 0x30B3
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y 0x30B5
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR 0x30B5
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z 0x30B7
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR 0x30B7
#define EGL_GL_TEXTURE_LEVEL 0x30BC
#define EGL_GL_TEXTURE_LEVEL_KHR 0x30BC
#define EGL_GL_TEXTURE_ZOFFSET 0x30BD
#define EGL_GL_TEXTURE_ZOFFSET_KHR 0x30BD
#define EGL_GREEN_SIZE 0x3023
#define EGL_HEIGHT 0x3056
#define EGL_HORIZONTAL_RESOLUTION 0x3090
#define EGL_IMAGE_PRESERVED 0x30D2
#define EGL_IMAGE_PRESERVED_KHR 0x30D2
#define EGL_IMPORT_EXPLICIT_SYNC_EXT 0x3472
#define EGL_IMPORT_IMPLICIT_SYNC_EXT 0x3471
#define EGL_IMPORT_SYNC_TYPE_EXT 0x3470
#define EGL_ITU_REC2020_EXT 0x3281
#define EGL_ITU_REC601_EXT 0x327F
#define EGL_ITU_REC709_EXT 0x3280
#define EGL_LARGEST_PBUFFER 0x3058
#define EGL_LAST_COMPOSITION_START_TIME_ANDROID 0x3438
#define EGL_LEFT_NV 0x336B
#define EGL_LEVEL 0x3029
#define EGL_LINUX_DMA_BUF_EXT 0x3270
#define EGL_LINUX_DRM_FOURCC_EXT 0x3271
#define EGL_LOCK_SURFACE_BIT_KHR 0x0080
#define EGL_LOCK_USAGE_HINT_KHR 0x30C5
#define EGL_LOSE_CONTEXT_ON_RESET 0x31BF
#define EGL_LOSE_CONTEXT_ON_RESET_EXT 0x31BF
#define EGL_LOSE_CONTEXT_ON_RESET_KHR 0x31BF
#define EGL_LOWER_LEFT_KHR 0x30CE
#define EGL_LUMINANCE_BUFFER 0x308F
#define EGL_LUMINANCE_SIZE 0x303D
#define EGL_MAP_PRESERVE_PIXELS_KHR 0x30C4
#define EGL_MATCH_FORMAT_KHR 0x3043
#define EGL_MATCH_NATIVE_PIXMAP 0x3041
#define EGL_MAX_PBUFFER_HEIGHT 0x302A
#define EGL_MAX_PBUFFER_PIXELS 0x302B
#define EGL_MAX_PBUFFER_WIDTH 0x302C
#define EGL_MAX_STREAM_METADATA_BLOCKS_NV 0x3250
#define EGL_MAX_STREAM_METADATA_BLOCK_SIZE_NV 0x3251
#define EGL_MAX_STREAM_METADATA_TOTAL_SIZE_NV 0x3252
#define EGL_MAX_SWAP_INTERVAL 0x303C
#define EGL_METADATA0_SIZE_NV 0x3255
#define EGL_METADATA0_TYPE_NV 0x3259
#define EGL_METADATA1_SIZE_NV 0x3256
#define EGL_METADATA1_TYPE_NV 0x325A
#define EGL_METADATA2_SIZE_NV 0x3257
#define EGL_METADATA2_TYPE_NV 0x325B
#define EGL_METADATA3_SIZE_NV 0x3258
#define EGL_METADATA3_TYPE_NV 0x325C
#define EGL_METADATA_SCALING_EXT 50000
#define EGL_MIN_SWAP_INTERVAL 0x303B
#define EGL_MIPMAP_LEVEL 0x3083
#define EGL_MIPMAP_TEXTURE 0x3082
#define EGL_MULTISAMPLE_RESOLVE 0x3099
#define EGL_MULTISAMPLE_RESOLVE_BOX 0x309B
#define EGL_MULTISAMPLE_RESOLVE_BOX_BIT 0x0200
#define EGL_MULTISAMPLE_RESOLVE_DEFAULT 0x309A
#define EGL_MULTIVIEW_VIEW_COUNT_EXT 0x3134
#define EGL_MUTABLE_RENDER_BUFFER_BIT_KHR 0x1000
#define EGL_NATIVE_BUFFER_ANDROID 0x3140
#define EGL_NATIVE_BUFFER_MULTIPLANE_SEPARATE_IMG 0x3105
#define EGL_NATIVE_BUFFER_PLANE_OFFSET_IMG 0x3106
#define EGL_NATIVE_BUFFER_QNX 0x3551
#define EGL_NATIVE_BUFFER_TIZEN 0x32A0
#define EGL_NATIVE_BUFFER_USAGE_ANDROID 0x3143
#define EGL_NATIVE_BUFFER_USAGE_PROTECTED_BIT_ANDROID 0x00000001
#define EGL_NATIVE_BUFFER_USAGE_RENDERBUFFER_BIT_ANDROID 0x00000002
#define EGL_NATIVE_BUFFER_USAGE_TEXTURE_BIT_ANDROID 0x00000004
#define EGL_NATIVE_PIXMAP_KHR 0x30B0
#define EGL_NATIVE_RENDERABLE 0x302D
#define EGL_NATIVE_SURFACE_TIZEN 0x32A1
#define EGL_NATIVE_VISUAL_ID 0x302E
#define EGL_NATIVE_VISUAL_TYPE 0x302F
#define EGL_NONE 0x3038
#define EGL_NON_CONFORMANT_CONFIG 0x3051
#define EGL_NOT_INITIALIZED 0x3001
#define EGL_NO_CONFIG_KHR EGL_CAST(EGLConfig,0)
#define EGL_NO_CONTEXT EGL_CAST(EGLContext,0)
#define EGL_NO_DEVICE_EXT EGL_CAST(EGLDeviceEXT,0)
#define EGL_NO_DISPLAY EGL_CAST(EGLDisplay,0)
#define EGL_NO_FILE_DESCRIPTOR_KHR EGL_CAST(EGLNativeFileDescriptorKHR,-1)
#define EGL_NO_IMAGE EGL_CAST(EGLImage,0)
#define EGL_NO_IMAGE_KHR EGL_CAST(EGLImageKHR,0)
#define EGL_NO_NATIVE_FENCE_FD_ANDROID -1
#define EGL_NO_OUTPUT_LAYER_EXT EGL_CAST(EGLOutputLayerEXT,0)
#define EGL_NO_OUTPUT_PORT_EXT EGL_CAST(EGLOutputPortEXT,0)
#define EGL_NO_RESET_NOTIFICATION 0x31BE
#define EGL_NO_RESET_NOTIFICATION_EXT 0x31BE
#define EGL_NO_RESET_NOTIFICATION_KHR 0x31BE
#define EGL_NO_STREAM_KHR EGL_CAST(EGLStreamKHR,0)
#define EGL_NO_SURFACE EGL_CAST(EGLSurface,0)
#define EGL_NO_SYNC EGL_CAST(EGLSync,0)
#define EGL_NO_SYNC_KHR EGL_CAST(EGLSync,0)
#define EGL_NO_SYNC_NV EGL_CAST(EGLSync,0)
#define EGL_NO_TEXTURE 0x305C
#define EGL_OBJECT_CONTEXT_KHR 0x33B2
#define EGL_OBJECT_DISPLAY_KHR 0x33B1
#define EGL_OBJECT_IMAGE_KHR 0x33B4
#define EGL_OBJECT_STREAM_KHR 0x33B6
#define EGL_OBJECT_SURFACE_KHR 0x33B3
#define EGL_OBJECT_SYNC_KHR 0x33B5
#define EGL_OBJECT_THREAD_KHR 0x33B0
#define EGL_OPENGL_API 0x30A2
#define EGL_OPENGL_BIT 0x0008
#define EGL_OPENGL_ES2_BIT 0x0004
#define EGL_OPENGL_ES3_BIT 0x00000040
#define EGL_OPENGL_ES3_BIT_KHR 0x00000040
#define EGL_OPENGL_ES_API 0x30A0
#define EGL_OPENGL_ES_BIT 0x0001
#define EGL_OPENVG_API 0x30A1
#define EGL_OPENVG_BIT 0x0002
#define EGL_OPENVG_IMAGE 0x3096
#define EGL_OPENWF_DEVICE_EXT 0x333D
#define EGL_OPENWF_DEVICE_ID_EXT 0x3237
#define EGL_OPENWF_PIPELINE_ID_EXT 0x3238
#define EGL_OPENWF_PORT_ID_EXT 0x3239
#define EGL_OPTIMAL_FORMAT_BIT_KHR 0x0100
#define EGL_PBUFFER_BIT 0x0001
#define EGL_PENDING_FRAME_NV 0x3329
#define EGL_PENDING_METADATA_NV 0x3328
#define EGL_PIXEL_ASPECT_RATIO 0x3092
#define EGL_PIXMAP_BIT 0x0002
#define EGL_PLATFORM_ANDROID_KHR 0x3141
#define EGL_PLATFORM_DEVICE_EXT 0x313F
#define EGL_PLATFORM_GBM_KHR 0x31D7
#define EGL_PLATFORM_GBM_MESA 0x31D7
#define EGL_PLATFORM_SCREEN_QNX 0x3550
#define EGL_PLATFORM_SURFACELESS_MESA 0x31DD
#define EGL_PLATFORM_WAYLAND_EXT 0x31D8
#define EGL_PLATFORM_WAYLAND_KHR 0x31D8
#define EGL_PLATFORM_X11_EXT 0x31D5
#define EGL_PLATFORM_X11_KHR 0x31D5
#define EGL_PLATFORM_X11_SCREEN_EXT 0x31D6
#define EGL_PLATFORM_X11_SCREEN_KHR 0x31D6
#define EGL_PLATFORM_XCB_EXT 0x31DC
#define EGL_PLATFORM_XCB_SCREEN_EXT 0x31DE
#define EGL_POST_SUB_BUFFER_SUPPORTED_NV 0x30BE
#define EGL_PRESENT_OPAQUE_EXT 0x31DF
#define EGL_PRIMARY_COMPOSITOR_CONTEXT_EXT 0x3460
#define EGL_PRODUCER_AUTO_ORIENTATION_NV 0x336A
#define EGL_PRODUCER_FRAME_KHR 0x3212
#define EGL_PRODUCER_MAX_FRAME_HINT_NV 0x3337
#define EGL_PRODUCER_METADATA_NV 0x3253
#define EGL_PROTECTED_CONTENT_EXT 0x32C0
#define EGL_QUADRUPLE_BUFFER_NV 0x3231
#define EGL_READ 0x305A
#define EGL_READS_DONE_TIME_ANDROID 0x343C
#define EGL_READ_SURFACE_BIT_KHR 0x0001
#define EGL_RECORDABLE_ANDROID 0x3142
#define EGL_RED_SIZE 0x3024
#define EGL_RENDERABLE_TYPE 0x3040
#define EGL_RENDERER_EXT 0x335F
#define EGL_RENDERING_COMPLETE_TIME_ANDROID 0x3435
#define EGL_RENDER_BUFFER 0x3086
#define EGL_REQUESTED_PRESENT_TIME_ANDROID 0x3434
#define EGL_RGB_BUFFER 0x308E
#define EGL_RIGHT_NV 0x336C
#define EGL_SAMPLES 0x3031
#define EGL_SAMPLE_BUFFERS 0x3032
#define EGL_SAMPLE_RANGE_HINT_EXT 0x327C
#define EGL_SIGNALED 0x30F2
#define EGL_SIGNALED_KHR 0x30F2
#define EGL_SIGNALED_NV 0x30E8
#define EGL_SINGLE_BUFFER 0x3085
#define EGL_SLOW_CONFIG 0x3050
#define EGL_SMPTE2086_DISPLAY_PRIMARY_BX_EXT 0x3345
#define EGL_SMPTE2086_DISPLAY_PRIMARY_BY_EXT 0x3346
#define EGL_SMPTE2086_DISPLAY_PRIMARY_GX_EXT 0x3343
#define EGL_SMPTE2086_DISPLAY_PRIMARY_GY_EXT 0x3344
#define EGL_SMPTE2086_DISPLAY_PRIMARY_RX_EXT 0x3341
#define EGL_SMPTE2086_DISPLAY_PRIMARY_RY_EXT 0x3342
#define EGL_SMPTE2086_MAX_LUMINANCE_EXT 0x3349
#define EGL_SMPTE2086_MIN_LUMINANCE_EXT 0x334A
#define EGL_SMPTE2086_WHITE_POINT_X_EXT 0x3347
#define EGL_SMPTE2086_WHITE_POINT_Y_EXT 0x3348
#define EGL_SOCKET_HANDLE_NV 0x324C
#define EGL_SOCKET_TYPE_INET_NV 0x324F
#define EGL_SOCKET_TYPE_NV 0x324D
#define EGL_SOCKET_TYPE_UNIX_NV 0x324E
#define EGL_STENCIL_SIZE 0x3026
#define EGL_STREAM_BIT_KHR 0x0800
#define EGL_STREAM_CONSUMER_IMAGE_NV 0x3373
#define EGL_STREAM_CONSUMER_IMAGE_USE_SCANOUT_NV 0x3378
#define EGL_STREAM_CONSUMER_NV 0x3248
#define EGL_STREAM_CROSS_DISPLAY_NV 0x334E
#define EGL_STREAM_CROSS_OBJECT_NV 0x334D
#define EGL_STREAM_CROSS_PARTITION_NV 0x323F
#define EGL_STREAM_CROSS_PROCESS_NV 0x3245
#define EGL_STREAM_CROSS_SYSTEM_NV 0x334F
#define EGL_STREAM_DMA_NV 0x3371
#define EGL_STREAM_DMA_SERVER_NV 0x3372
#define EGL_STREAM_ENDPOINT_NV 0x3243
#define EGL_STREAM_FIFO_LENGTH_KHR 0x31FC
#define EGL_STREAM_FIFO_SYNCHRONOUS_NV 0x3336
#define EGL_STREAM_FRAME_MAJOR_AXIS_NV 0x3368
#define EGL_STREAM_FRAME_ORIGIN_X_NV 0x3366
#define EGL_STREAM_FRAME_ORIGIN_Y_NV 0x3367
#define EGL_STREAM_IMAGE_ADD_NV 0x3374
#define EGL_STREAM_IMAGE_AVAILABLE_NV 0x3376
#define EGL_STREAM_IMAGE_REMOVE_NV 0x3375
#define EGL_STREAM_LOCAL_NV 0x3244
#define EGL_STREAM_PRODUCER_NV 0x3247
#define EGL_STREAM_PROTOCOL_FD_NV 0x3246
#define EGL_STREAM_PROTOCOL_NV 0x3242
#define EGL_STREAM_PROTOCOL_SOCKET_NV 0x324B
#define EGL_STREAM_STATE_CONNECTING_KHR 0x3216
#define EGL_STREAM_STATE_CREATED_KHR 0x3215
#define EGL_STREAM_STATE_DISCONNECTED_KHR 0x321A
#define EGL_STREAM_STATE_EMPTY_KHR 0x3217
#define EGL_STREAM_STATE_INITIALIZING_NV 0x3240
#define EGL_STREAM_STATE_KHR 0x3214
#define EGL_STREAM_STATE_NEW_FRAME_AVAILABLE_KHR 0x3218
#define EGL_STREAM_STATE_OLD_FRAME_AVAILABLE_KHR 0x3219
#define EGL_STREAM_TIME_CONSUMER_KHR 0x31FE
#define EGL_STREAM_TIME_NOW_KHR 0x31FD
#define EGL_STREAM_TIME_PENDING_NV 0x332A
#define EGL_STREAM_TIME_PRODUCER_KHR 0x31FF
#define EGL_STREAM_TYPE_NV 0x3241
#define EGL_SUCCESS 0x3000
#define EGL_SUPPORT_RESET_NV 0x3334
#define EGL_SUPPORT_REUSE_NV 0x3335
#define EGL_SURFACE_COMPRESSION_EXT 0x34B0
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_10BPC_EXT 0x34BD
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_11BPC_EXT 0x34BE
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_12BPC_EXT 0x34BF
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_1BPC_EXT 0x34B4
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_2BPC_EXT 0x34B5
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_3BPC_EXT 0x34B6
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_4BPC_EXT 0x34B7
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_5BPC_EXT 0x34B8
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_6BPC_EXT 0x34B9
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_7BPC_EXT 0x34BA
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_8BPC_EXT 0x34BB
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_9BPC_EXT 0x34BC
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_DEFAULT_EXT 0x34B2
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_NONE_EXT 0x34B1
#define EGL_SURFACE_COMPRESSION_PLANE1_EXT 0x328E
#define EGL_SURFACE_COMPRESSION_PLANE2_EXT 0x328F
#define EGL_SURFACE_TYPE 0x3033
#define EGL_SWAP_BEHAVIOR 0x3093
#define EGL_SWAP_BEHAVIOR_PRESERVED_BIT 0x0400
#define EGL_SWAP_INTERVAL_EXT 0x322F
#define EGL_SYNC_CLIENT_EXT 0x3364
#define EGL_SYNC_CLIENT_SIGNAL_EXT 0x3365
#define EGL_SYNC_CL_EVENT 0x30FE
#define EGL_SYNC_CL_EVENT_COMPLETE 0x30FF
#define EGL_SYNC_CL_EVENT_COMPLETE_KHR 0x30FF
#define EGL_SYNC_CL_EVENT_KHR 0x30FE
#define EGL_SYNC_CONDITION 0x30F8
#define EGL_SYNC_CONDITION_KHR 0x30F8
#define EGL_SYNC_CONDITION_NV 0x30EE
#define EGL_SYNC_CUDA_EVENT_COMPLETE_NV 0x323D
#define EGL_SYNC_CUDA_EVENT_NV 0x323C
#define EGL_SYNC_FENCE 0x30F9
#define EGL_SYNC_FENCE_KHR 0x30F9
#define EGL_SYNC_FENCE_NV 0x30EF
#define EGL_SYNC_FLUSH_COMMANDS_BIT 0x0001
#define EGL_SYNC_FLUSH_COMMANDS_BIT_KHR 0x0001
#define EGL_SYNC_FLUSH_COMMANDS_BIT_NV 0x0001
#define EGL_SYNC_NATIVE_FENCE_ANDROID 0x3144
#define EGL_SYNC_NATIVE_FENCE_FD_ANDROID 0x3145
#define EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID 0x3146
#define EGL_SYNC_NEW_FRAME_NV 0x321F
#define EGL_SYNC_PRIOR_COMMANDS_COMPLETE 0x30F0
#define EGL_SYNC_PRIOR_COMMANDS_COMPLETE_KHR 0x30F0
#define EGL_SYNC_PRIOR_COMMANDS_COMPLETE_NV 0x30E6
#define EGL_SYNC_PRIOR_COMMANDS_IMPLICIT_EXTERNAL_ARM 0x328A
#define EGL_SYNC_REUSABLE_KHR 0x30FA
#define EGL_SYNC_STATUS 0x30F1
#define EGL_SYNC_STATUS_KHR 0x30F1
#define EGL_SYNC_STATUS_NV 0x30E7
#define EGL_SYNC_TYPE 0x30F7
#define EGL_SYNC_TYPE_KHR 0x30F7
#define EGL_SYNC_TYPE_NV 0x30ED
#define EGL_TELEMETRY_HINT_ANDROID 0x3570
#define EGL_TEXTURE_2D 0x305F
#define EGL_TEXTURE_EXTERNAL_WL 0x31DA
#define EGL_TEXTURE_FORMAT 0x3080
#define EGL_TEXTURE_RGB 0x305D
#define EGL_TEXTURE_RGBA 0x305E
#define EGL_TEXTURE_TARGET 0x3081
#define EGL_TEXTURE_Y_UV_WL 0x31D8
#define EGL_TEXTURE_Y_U_V_WL 0x31D7
#define EGL_TEXTURE_Y_XUXV_WL 0x31D9
#define EGL_TIMEOUT_EXPIRED 0x30F5
#define EGL_TIMEOUT_EXPIRED_KHR 0x30F5
#define EGL_TIMEOUT_EXPIRED_NV 0x30EB
#define EGL_TIMESTAMPS_ANDROID 0x3430
#define EGL_TIMESTAMP_INVALID_ANDROID EGL_CAST(EGLnsecsANDROID,-1)
#define EGL_TIMESTAMP_PENDING_ANDROID EGL_CAST(EGLnsecsANDROID,-2)
#define EGL_TOP_NV 0x336D
#define EGL_TRACK_REFERENCES_KHR 0x3352
#define EGL_TRANSPARENT_BLUE_VALUE 0x3035
#define EGL_TRANSPARENT_GREEN_VALUE 0x3036
#define EGL_TRANSPARENT_RED_VALUE 0x3037
#define EGL_TRANSPARENT_RGB 0x3052
#define EGL_TRANSPARENT_TYPE 0x3034
#define EGL_TRIPLE_BUFFER_NV 0x3230
#define EGL_TRUE 1
#define EGL_UNKNOWN EGL_CAST(EGLint,-1)
#define EGL_UNSIGNALED 0x30F3
#define EGL_UNSIGNALED_KHR 0x30F3
#define EGL_UNSIGNALED_NV 0x30E9
#define EGL_UPPER_LEFT_KHR 0x30CF
#define EGL_VENDOR 0x3053
#define EGL_VERSION 0x3054
#define EGL_VERTICAL_RESOLUTION 0x3091
#define EGL_VG_ALPHA_FORMAT 0x3088
#define EGL_VG_ALPHA_FORMAT_NONPRE 0x308B
#define EGL_VG_ALPHA_FORMAT_PRE 0x308C
#define EGL_VG_ALPHA_FORMAT_PRE_BIT 0x0040
#define EGL_VG_ALPHA_FORMAT_PRE_BIT_KHR 0x0040
#define EGL_VG_COLORSPACE 0x3087
#define EGL_VG_COLORSPACE_LINEAR 0x308A
#define EGL_VG_COLORSPACE_LINEAR_BIT 0x0020
#define EGL_VG_COLORSPACE_LINEAR_BIT_KHR 0x0020
#define EGL_VG_COLORSPACE_sRGB 0x3089
#define EGL_VG_PARENT_IMAGE_KHR 0x30BA
#define EGL_WAYLAND_BUFFER_WL 0x31D5
#define EGL_WAYLAND_PLANE_WL 0x31D6
#define EGL_WAYLAND_Y_INVERTED_WL 0x31DB
#define EGL_WIDTH 0x3057
#define EGL_WINDOW_BIT 0x0004
#define EGL_WRITE_SURFACE_BIT_KHR 0x0002
#define EGL_X_AXIS_NV 0x336F
#define EGL_YUV_BUFFER_EXT 0x3300
#define EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT 0x327D
#define EGL_YUV_CHROMA_SITING_0_5_EXT 0x3285
#define EGL_YUV_CHROMA_SITING_0_EXT 0x3284
#define EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT 0x327E
#define EGL_YUV_COLOR_SPACE_HINT_EXT 0x327B
#define EGL_YUV_CSC_STANDARD_2020_EXT 0x330D
#define EGL_YUV_CSC_STANDARD_601_EXT 0x330B
#define EGL_YUV_CSC_STANDARD_709_EXT 0x330C
#define EGL_YUV_CSC_STANDARD_EXT 0x330A
#define EGL_YUV_DEPTH_RANGE_EXT 0x3317
#define EGL_YUV_DEPTH_RANGE_FULL_EXT 0x3319
#define EGL_YUV_DEPTH_RANGE_LIMITED_EXT 0x3318
#define EGL_YUV_FULL_RANGE_EXT 0x3282
#define EGL_YUV_NARROW_RANGE_EXT 0x3283
#define EGL_YUV_NUMBER_OF_PLANES_EXT 0x3311
#define EGL_YUV_ORDER_AYUV_EXT 0x3308
#define EGL_YUV_ORDER_EXT 0x3301
#define EGL_YUV_ORDER_UYVY_EXT 0x3305
#define EGL_YUV_ORDER_VYUY_EXT 0x3307
#define EGL_YUV_ORDER_YUV_EXT 0x3302
#define EGL_YUV_ORDER_YUYV_EXT 0x3304
#define EGL_YUV_ORDER_YVU_EXT 0x3303
#define EGL_YUV_ORDER_YVYU_EXT 0x3306
#define EGL_YUV_PLANE0_TEXTURE_UNIT_NV 0x332C
#define EGL_YUV_PLANE1_TEXTURE_UNIT_NV 0x332D
#define EGL_YUV_PLANE2_TEXTURE_UNIT_NV 0x332E
#define EGL_YUV_PLANE_BPP_0_EXT 0x331B
#define EGL_YUV_PLANE_BPP_10_EXT 0x331D
#define EGL_YUV_PLANE_BPP_8_EXT 0x331C
#define EGL_YUV_PLANE_BPP_EXT 0x331A
#define EGL_YUV_SUBSAMPLE_4_2_0_EXT 0x3313
#define EGL_YUV_SUBSAMPLE_4_2_2_EXT 0x3314
#define EGL_YUV_SUBSAMPLE_4_4_4_EXT 0x3315
#define EGL_YUV_SUBSAMPLE_EXT 0x3312
#define EGL_Y_AXIS_NV 0x3370
#define EGL_Y_INVERTED_NOK 0x307F


#include <KHR/khrplatform.h>
#include <EGL/eglplatform.h>











struct AHardwareBuffer;
struct wl_buffer;
struct wl_display;
struct wl_resource;

typedef unsigned int EGLBoolean;
typedef unsigned int EGLenum;
typedef intptr_t EGLAttribKHR;
typedef intptr_t EGLAttrib;
typedef void *EGLClientBuffer;
typedef void *EGLConfig;
typedef void *EGLContext;
typedef void *EGLDeviceEXT;
typedef void *EGLDisplay;
typedef void *EGLImage;
typedef void *EGLImageKHR;
typedef void *EGLLabelKHR;
typedef void *EGLObjectKHR;
typedef void *EGLOutputLayerEXT;
typedef void *EGLOutputPortEXT;
typedef void *EGLStreamKHR;
typedef void *EGLSurface;
typedef void *EGLSync;
typedef void *EGLSyncKHR;
typedef void *EGLSyncNV;
typedef void (*__eglMustCastToProperFunctionPointerType)(void);
typedef khronos_utime_nanoseconds_t EGLTimeKHR;
typedef khronos_utime_nanoseconds_t EGLTime;
typedef khronos_utime_nanoseconds_t EGLTimeNV;
typedef khronos_utime_nanoseconds_t EGLuint64NV;
typedef khronos_uint64_t EGLuint64KHR;
typedef khronos_stime_nanoseconds_t EGLnsecsANDROID;
typedef int EGLNativeFileDescriptorKHR;
typedef khronos_ssize_t EGLsizeiANDROID;
typedef void (*EGLSetBlobFuncANDROID) (const void *key, EGLsizeiANDROID keySize, const void *value, EGLsizeiANDROID valueSize);
typedef EGLsizeiANDROID (*EGLGetBlobFuncANDROID) (const void *key, EGLsizeiANDROID keySize, void *value, EGLsizeiANDROID valueSize);
struct EGLClientPixmapHI {
    void  *pData;
    EGLint iWidth;
    EGLint iHeight;
    EGLint iStride;
};
typedef void (GLO_API_PTR *EGLDEBUGPROCKHR)(EGLenum error,const char *command,EGLint messageType,EGLLabelKHR threadLabel,EGLLabelKHR objectLabel,const char* message);
#define PFNEGLBINDWAYLANDDISPLAYWL PFNEGLBINDWAYLANDDISPLAYWLPROC
#define PFNEGLUNBINDWAYLANDDISPLAYWL PFNEGLUNBINDWAYLANDDISPLAYWLPROC
#define PFNEGLQUERYWAYLANDBUFFERWL PFNEGLQUERYWAYLANDBUFFERWLPROC
#define PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWL PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC


#define EGL_VERSION_1_0 1
GLO_API_CALL int GLO_EGL_VERSION_1_0;
#define EGL_VERSION_1_1 1
GLO_API_CALL int GLO_EGL_VERSION_1_1;
#define EGL_VERSION_1_2 1
GLO_API_CALL int GLO_EGL_VERSION_1_2;
#define EGL_VERSION_1_3 1
GLO_API_CALL int GLO_EGL_VERSION_1_3;
#define EGL_VERSION_1_4 1
GLO_API_CALL int GLO_EGL_VERSION_1_4;
#define EGL_VERSION_1_5 1
GLO_API_CALL int GLO_EGL_VERSION_1_5;
#define EGL_ANDROID_GLES_layers 1
GLO_API_CALL int GLO_EGL_ANDROID_GLES_layers;
#define EGL_ANDROID_blob_cache 1
GLO_API_CALL int GLO_EGL_ANDROID_blob_cache;
#define EGL_ANDROID_create_native_client_buffer 1
GLO_API_CALL int GLO_EGL_ANDROID_create_native_client_buffer;
#define EGL_ANDROID_framebuffer_target 1
GLO_API_CALL int GLO_EGL_ANDROID_framebuffer_target;
#define EGL_ANDROID_front_buffer_auto_refresh 1
GLO_API_CALL int GLO_EGL_ANDROID_front_buffer_auto_refresh;
#define EGL_ANDROID_get_frame_timestamps 1
GLO_API_CALL int GLO_EGL_ANDROID_get_frame_timestamps;
#define EGL_ANDROID_get_native_client_buffer 1
GLO_API_CALL int GLO_EGL_ANDROID_get_native_client_buffer;
#define EGL_ANDROID_image_native_buffer 1
GLO_API_CALL int GLO_EGL_ANDROID_image_native_buffer;
#define EGL_ANDROID_native_fence_sync 1
GLO_API_CALL int GLO_EGL_ANDROID_native_fence_sync;
#define EGL_ANDROID_presentation_time 1
GLO_API_CALL int GLO_EGL_ANDROID_presentation_time;
#define EGL_ANDROID_recordable 1
GLO_API_CALL int GLO_EGL_ANDROID_recordable;
#define EGL_ANDROID_telemetry_hint 1
GLO_API_CALL int GLO_EGL_ANDROID_telemetry_hint;
#define EGL_ANGLE_d3d_share_handle_client_buffer 1
GLO_API_CALL int GLO_EGL_ANGLE_d3d_share_handle_client_buffer;
#define EGL_ANGLE_device_d3d 1
GLO_API_CALL int GLO_EGL_ANGLE_device_d3d;
#define EGL_ANGLE_query_surface_pointer 1
GLO_API_CALL int GLO_EGL_ANGLE_query_surface_pointer;
#define EGL_ANGLE_surface_d3d_texture_2d_share_handle 1
GLO_API_CALL int GLO_EGL_ANGLE_surface_d3d_texture_2d_share_handle;
#define EGL_ANGLE_sync_control_rate 1
GLO_API_CALL int GLO_EGL_ANGLE_sync_control_rate;
#define EGL_ANGLE_window_fixed_size 1
GLO_API_CALL int GLO_EGL_ANGLE_window_fixed_size;
#define EGL_ARM_image_format 1
GLO_API_CALL int GLO_EGL_ARM_image_format;
#define EGL_ARM_implicit_external_sync 1
GLO_API_CALL int GLO_EGL_ARM_implicit_external_sync;
#define EGL_ARM_pixmap_multisample_discard 1
GLO_API_CALL int GLO_EGL_ARM_pixmap_multisample_discard;
#define EGL_EXT_bind_to_front 1
GLO_API_CALL int GLO_EGL_EXT_bind_to_front;
#define EGL_EXT_buffer_age 1
GLO_API_CALL int GLO_EGL_EXT_buffer_age;
#define EGL_EXT_client_extensions 1
GLO_API_CALL int GLO_EGL_EXT_client_extensions;
#define EGL_EXT_client_sync 1
GLO_API_CALL int GLO_EGL_EXT_client_sync;
#define EGL_EXT_compositor 1
GLO_API_CALL int GLO_EGL_EXT_compositor;
#define EGL_EXT_config_select_group 1
GLO_API_CALL int GLO_EGL_EXT_config_select_group;
#define EGL_EXT_create_context_robustness 1
GLO_API_CALL int GLO_EGL_EXT_create_context_robustness;
#define EGL_EXT_device_base 1
GLO_API_CALL int GLO_EGL_EXT_device_base;
#define EGL_EXT_device_drm 1
GLO_API_CALL int GLO_EGL_EXT_device_drm;
#define EGL_EXT_device_drm_render_node 1
GLO_API_CALL int GLO_EGL_EXT_device_drm_render_node;
#define EGL_EXT_device_enumeration 1
GLO_API_CALL int GLO_EGL_EXT_device_enumeration;
#define EGL_EXT_device_openwf 1
GLO_API_CALL int GLO_EGL_EXT_device_openwf;
#define EGL_EXT_device_persistent_id 1
GLO_API_CALL int GLO_EGL_EXT_device_persistent_id;
#define EGL_EXT_device_query 1
GLO_API_CALL int GLO_EGL_EXT_device_query;
#define EGL_EXT_device_query_name 1
GLO_API_CALL int GLO_EGL_EXT_device_query_name;
#define EGL_EXT_display_alloc 1
GLO_API_CALL int GLO_EGL_EXT_display_alloc;
#define EGL_EXT_explicit_device 1
GLO_API_CALL int GLO_EGL_EXT_explicit_device;
#define EGL_EXT_gl_colorspace_bt2020_hlg 1
GLO_API_CALL int GLO_EGL_EXT_gl_colorspace_bt2020_hlg;
#define EGL_EXT_gl_colorspace_bt2020_linear 1
GLO_API_CALL int GLO_EGL_EXT_gl_colorspace_bt2020_linear;
#define EGL_EXT_gl_colorspace_bt2020_pq 1
GLO_API_CALL int GLO_EGL_EXT_gl_colorspace_bt2020_pq;
#define EGL_EXT_gl_colorspace_display_p3 1
GLO_API_CALL int GLO_EGL_EXT_gl_colorspace_display_p3;
#define EGL_EXT_gl_colorspace_display_p3_linear 1
GLO_API_CALL int GLO_EGL_EXT_gl_colorspace_display_p3_linear;
#define EGL_EXT_gl_colorspace_display_p3_passthrough 1
GLO_API_CALL int GLO_EGL_EXT_gl_colorspace_display_p3_passthrough;
#define EGL_EXT_gl_colorspace_scrgb 1
GLO_API_CALL int GLO_EGL_EXT_gl_colorspace_scrgb;
#define EGL_EXT_gl_colorspace_scrgb_linear 1
GLO_API_CALL int GLO_EGL_EXT_gl_colorspace_scrgb_linear;
#define EGL_EXT_image_dma_buf_import 1
GLO_API_CALL int GLO_EGL_EXT_image_dma_buf_import;
#define EGL_EXT_image_dma_buf_import_modifiers 1
GLO_API_CALL int GLO_EGL_EXT_image_dma_buf_import_modifiers;
#define EGL_EXT_image_gl_colorspace 1
GLO_API_CALL int GLO_EGL_EXT_image_gl_colorspace;
#define EGL_EXT_image_implicit_sync_control 1
GLO_API_CALL int GLO_EGL_EXT_image_implicit_sync_control;
#define EGL_EXT_multiview_window 1
GLO_API_CALL int GLO_EGL_EXT_multiview_window;
#define EGL_EXT_output_base 1
GLO_API_CALL int GLO_EGL_EXT_output_base;
#define EGL_EXT_output_drm 1
GLO_API_CALL int GLO_EGL_EXT_output_drm;
#define EGL_EXT_output_openwf 1
GLO_API_CALL int GLO_EGL_EXT_output_openwf;
#define EGL_EXT_pixel_format_float 1
GLO_API_CALL int GLO_EGL_EXT_pixel_format_float;
#define EGL_EXT_platform_base 1
GLO_API_CALL int GLO_EGL_EXT_platform_base;
#define EGL_EXT_platform_device 1
GLO_API_CALL int GLO_EGL_EXT_platform_device;
#define EGL_EXT_platform_wayland 1
GLO_API_CALL int GLO_EGL_EXT_platform_wayland;
#define EGL_EXT_platform_x11 1
GLO_API_CALL int GLO_EGL_EXT_platform_x11;
#define EGL_EXT_platform_xcb 1
GLO_API_CALL int GLO_EGL_EXT_platform_xcb;
#define EGL_EXT_present_opaque 1
GLO_API_CALL int GLO_EGL_EXT_present_opaque;
#define EGL_EXT_protected_content 1
GLO_API_CALL int GLO_EGL_EXT_protected_content;
#define EGL_EXT_protected_surface 1
GLO_API_CALL int GLO_EGL_EXT_protected_surface;
#define EGL_EXT_query_reset_notification_strategy 1
GLO_API_CALL int GLO_EGL_EXT_query_reset_notification_strategy;
#define EGL_EXT_stream_consumer_egloutput 1
GLO_API_CALL int GLO_EGL_EXT_stream_consumer_egloutput;
#define EGL_EXT_surface_CTA861_3_metadata 1
GLO_API_CALL int GLO_EGL_EXT_surface_CTA861_3_metadata;
#define EGL_EXT_surface_SMPTE2086_metadata 1
GLO_API_CALL int GLO_EGL_EXT_surface_SMPTE2086_metadata;
#define EGL_EXT_surface_compression 1
GLO_API_CALL int GLO_EGL_EXT_surface_compression;
#define EGL_EXT_swap_buffers_with_damage 1
GLO_API_CALL int GLO_EGL_EXT_swap_buffers_with_damage;
#define EGL_EXT_sync_reuse 1
GLO_API_CALL int GLO_EGL_EXT_sync_reuse;
#define EGL_EXT_yuv_surface 1
GLO_API_CALL int GLO_EGL_EXT_yuv_surface;
#define EGL_HI_clientpixmap 1
GLO_API_CALL int GLO_EGL_HI_clientpixmap;
#define EGL_HI_colorformats 1
GLO_API_CALL int GLO_EGL_HI_colorformats;
#define EGL_IMG_context_priority 1
GLO_API_CALL int GLO_EGL_IMG_context_priority;
#define EGL_IMG_image_plane_attribs 1
GLO_API_CALL int GLO_EGL_IMG_image_plane_attribs;
#define EGL_KHR_cl_event 1
GLO_API_CALL int GLO_EGL_KHR_cl_event;
#define EGL_KHR_cl_event2 1
GLO_API_CALL int GLO_EGL_KHR_cl_event2;
#define EGL_KHR_client_get_all_proc_addresses 1
GLO_API_CALL int GLO_EGL_KHR_client_get_all_proc_addresses;
#define EGL_KHR_config_attribs 1
GLO_API_CALL int GLO_EGL_KHR_config_attribs;
#define EGL_KHR_context_flush_control 1
GLO_API_CALL int GLO_EGL_KHR_context_flush_control;
#define EGL_KHR_create_context 1
GLO_API_CALL int GLO_EGL_KHR_create_context;
#define EGL_KHR_create_context_no_error 1
GLO_API_CALL int GLO_EGL_KHR_create_context_no_error;
#define EGL_KHR_debug 1
GLO_API_CALL int GLO_EGL_KHR_debug;
#define EGL_KHR_display_reference 1
GLO_API_CALL int GLO_EGL_KHR_display_reference;
#define EGL_KHR_fence_sync 1
GLO_API_CALL int GLO_EGL_KHR_fence_sync;
#define EGL_KHR_get_all_proc_addresses 1
GLO_API_CALL int GLO_EGL_KHR_get_all_proc_addresses;
#define EGL_KHR_gl_colorspace 1
GLO_API_CALL int GLO_EGL_KHR_gl_colorspace;
#define EGL_KHR_gl_renderbuffer_image 1
GLO_API_CALL int GLO_EGL_KHR_gl_renderbuffer_image;
#define EGL_KHR_gl_texture_2D_image 1
GLO_API_CALL int GLO_EGL_KHR_gl_texture_2D_image;
#define EGL_KHR_gl_texture_3D_image 1
GLO_API_CALL int GLO_EGL_KHR_gl_texture_3D_image;
#define EGL_KHR_gl_texture_cubemap_image 1
GLO_API_CALL int GLO_EGL_KHR_gl_texture_cubemap_image;
#define EGL_KHR_image 1
GLO_API_CALL int GLO_EGL_KHR_image;
#define EGL_KHR_image_base 1
GLO_API_CALL int GLO_EGL_KHR_image_base;
#define EGL_KHR_image_pixmap 1
GLO_API_CALL int GLO_EGL_KHR_image_pixmap;
#define EGL_KHR_lock_surface 1
GLO_API_CALL int GLO_EGL_KHR_lock_surface;
#define EGL_KHR_lock_surface2 1
GLO_API_CALL int GLO_EGL_KHR_lock_surface2;
#define EGL_KHR_lock_surface3 1
GLO_API_CALL int GLO_EGL_KHR_lock_surface3;
#define EGL_KHR_mutable_render_buffer 1
GLO_API_CALL int GLO_EGL_KHR_mutable_render_buffer;
#define EGL_KHR_no_config_context 1
GLO_API_CALL int GLO_EGL_KHR_no_config_context;
#define EGL_KHR_partial_update 1
GLO_API_CALL int GLO_EGL_KHR_partial_update;
#define EGL_KHR_platform_android 1
GLO_API_CALL int GLO_EGL_KHR_platform_android;
#define EGL_KHR_platform_gbm 1
GLO_API_CALL int GLO_EGL_KHR_platform_gbm;
#define EGL_KHR_platform_wayland 1
GLO_API_CALL int GLO_EGL_KHR_platform_wayland;
#define EGL_KHR_platform_x11 1
GLO_API_CALL int GLO_EGL_KHR_platform_x11;
#define EGL_KHR_reusable_sync 1
GLO_API_CALL int GLO_EGL_KHR_reusable_sync;
#define EGL_KHR_stream 1
GLO_API_CALL int GLO_EGL_KHR_stream;
#define EGL_KHR_stream_attrib 1
GLO_API_CALL int GLO_EGL_KHR_stream_attrib;
#define EGL_KHR_stream_consumer_gltexture 1
GLO_API_CALL int GLO_EGL_KHR_stream_consumer_gltexture;
#define EGL_KHR_stream_cross_process_fd 1
GLO_API_CALL int GLO_EGL_KHR_stream_cross_process_fd;
#define EGL_KHR_stream_fifo 1
GLO_API_CALL int GLO_EGL_KHR_stream_fifo;
#define EGL_KHR_stream_producer_aldatalocator 1
GLO_API_CALL int GLO_EGL_KHR_stream_producer_aldatalocator;
#define EGL_KHR_stream_producer_eglsurface 1
GLO_API_CALL int GLO_EGL_KHR_stream_producer_eglsurface;
#define EGL_KHR_surfaceless_context 1
GLO_API_CALL int GLO_EGL_KHR_surfaceless_context;
#define EGL_KHR_swap_buffers_with_damage 1
GLO_API_CALL int GLO_EGL_KHR_swap_buffers_with_damage;
#define EGL_KHR_vg_parent_image 1
GLO_API_CALL int GLO_EGL_KHR_vg_parent_image;
#define EGL_KHR_wait_sync 1
GLO_API_CALL int GLO_EGL_KHR_wait_sync;
#define EGL_MESA_drm_image 1
GLO_API_CALL int GLO_EGL_MESA_drm_image;
#define EGL_MESA_image_dma_buf_export 1
GLO_API_CALL int GLO_EGL_MESA_image_dma_buf_export;
#define EGL_MESA_platform_gbm 1
GLO_API_CALL int GLO_EGL_MESA_platform_gbm;
#define EGL_MESA_platform_surfaceless 1
GLO_API_CALL int GLO_EGL_MESA_platform_surfaceless;
#define EGL_MESA_query_driver 1
GLO_API_CALL int GLO_EGL_MESA_query_driver;
#define EGL_NOK_swap_region 1
GLO_API_CALL int GLO_EGL_NOK_swap_region;
#define EGL_NOK_swap_region2 1
GLO_API_CALL int GLO_EGL_NOK_swap_region2;
#define EGL_NOK_texture_from_pixmap 1
GLO_API_CALL int GLO_EGL_NOK_texture_from_pixmap;
#define EGL_NV_3dvision_surface 1
GLO_API_CALL int GLO_EGL_NV_3dvision_surface;
#define EGL_NV_context_priority_realtime 1
GLO_API_CALL int GLO_EGL_NV_context_priority_realtime;
#define EGL_NV_coverage_sample 1
GLO_API_CALL int GLO_EGL_NV_coverage_sample;
#define EGL_NV_coverage_sample_resolve 1
GLO_API_CALL int GLO_EGL_NV_coverage_sample_resolve;
#define EGL_NV_cuda_event 1
GLO_API_CALL int GLO_EGL_NV_cuda_event;
#define EGL_NV_depth_nonlinear 1
GLO_API_CALL int GLO_EGL_NV_depth_nonlinear;
#define EGL_NV_device_cuda 1
GLO_API_CALL int GLO_EGL_NV_device_cuda;
#define EGL_NV_native_query 1
GLO_API_CALL int GLO_EGL_NV_native_query;
#define EGL_NV_post_convert_rounding 1
GLO_API_CALL int GLO_EGL_NV_post_convert_rounding;
#define EGL_NV_post_sub_buffer 1
GLO_API_CALL int GLO_EGL_NV_post_sub_buffer;
#define EGL_NV_quadruple_buffer 1
GLO_API_CALL int GLO_EGL_NV_quadruple_buffer;
#define EGL_NV_robustness_video_memory_purge 1
GLO_API_CALL int GLO_EGL_NV_robustness_video_memory_purge;
#define EGL_NV_stream_consumer_eglimage 1
GLO_API_CALL int GLO_EGL_NV_stream_consumer_eglimage;
#define EGL_NV_stream_consumer_eglimage_use_scanout_attrib 1
GLO_API_CALL int GLO_EGL_NV_stream_consumer_eglimage_use_scanout_attrib;
#define EGL_NV_stream_consumer_gltexture_yuv 1
GLO_API_CALL int GLO_EGL_NV_stream_consumer_gltexture_yuv;
#define EGL_NV_stream_cross_display 1
GLO_API_CALL int GLO_EGL_NV_stream_cross_display;
#define EGL_NV_stream_cross_object 1
GLO_API_CALL int GLO_EGL_NV_stream_cross_object;
#define EGL_NV_stream_cross_partition 1
GLO_API_CALL int GLO_EGL_NV_stream_cross_partition;
#define EGL_NV_stream_cross_process 1
GLO_API_CALL int GLO_EGL_NV_stream_cross_process;
#define EGL_NV_stream_cross_system 1
GLO_API_CALL int GLO_EGL_NV_stream_cross_system;
#define EGL_NV_stream_dma 1
GLO_API_CALL int GLO_EGL_NV_stream_dma;
#define EGL_NV_stream_fifo_next 1
GLO_API_CALL int GLO_EGL_NV_stream_fifo_next;
#define EGL_NV_stream_fifo_synchronous 1
GLO_API_CALL int GLO_EGL_NV_stream_fifo_synchronous;
#define EGL_NV_stream_flush 1
GLO_API_CALL int GLO_EGL_NV_stream_flush;
#define EGL_NV_stream_frame_limits 1
GLO_API_CALL int GLO_EGL_NV_stream_frame_limits;
#define EGL_NV_stream_metadata 1
GLO_API_CALL int GLO_EGL_NV_stream_metadata;
#define EGL_NV_stream_origin 1
GLO_API_CALL int GLO_EGL_NV_stream_origin;
#define EGL_NV_stream_remote 1
GLO_API_CALL int GLO_EGL_NV_stream_remote;
#define EGL_NV_stream_reset 1
GLO_API_CALL int GLO_EGL_NV_stream_reset;
#define EGL_NV_stream_socket 1
GLO_API_CALL int GLO_EGL_NV_stream_socket;
#define EGL_NV_stream_socket_inet 1
GLO_API_CALL int GLO_EGL_NV_stream_socket_inet;
#define EGL_NV_stream_socket_unix 1
GLO_API_CALL int GLO_EGL_NV_stream_socket_unix;
#define EGL_NV_stream_sync 1
GLO_API_CALL int GLO_EGL_NV_stream_sync;
#define EGL_NV_sync 1
GLO_API_CALL int GLO_EGL_NV_sync;
#define EGL_NV_system_time 1
GLO_API_CALL int GLO_EGL_NV_system_time;
#define EGL_NV_triple_buffer 1
GLO_API_CALL int GLO_EGL_NV_triple_buffer;
#define EGL_QNX_image_native_buffer 1
GLO_API_CALL int GLO_EGL_QNX_image_native_buffer;
#define EGL_QNX_platform_screen 1
GLO_API_CALL int GLO_EGL_QNX_platform_screen;
#define EGL_TIZEN_image_native_buffer 1
GLO_API_CALL int GLO_EGL_TIZEN_image_native_buffer;
#define EGL_TIZEN_image_native_surface 1
GLO_API_CALL int GLO_EGL_TIZEN_image_native_surface;
#define EGL_WL_bind_wayland_display 1
GLO_API_CALL int GLO_EGL_WL_bind_wayland_display;
#define EGL_WL_create_wayland_buffer_from_image 1
GLO_API_CALL int GLO_EGL_WL_create_wayland_buffer_from_image;


typedef EGLBoolean (GLO_API_PTR *PFNEGLBINDAPIPROC)(EGLenum api);
typedef EGLBoolean (GLO_API_PTR *PFNEGLBINDTEXIMAGEPROC)(EGLDisplay dpy, EGLSurface surface, EGLint buffer);
typedef EGLBoolean (GLO_API_PTR *PFNEGLBINDWAYLANDDISPLAYWLPROC)(EGLDisplay dpy, struct wl_display * display);
typedef EGLBoolean (GLO_API_PTR *PFNEGLCHOOSECONFIGPROC)(EGLDisplay dpy, const EGLint * attrib_list, EGLConfig * configs, EGLint config_size, EGLint * num_config);
typedef EGLBoolean (GLO_API_PTR *PFNEGLCLIENTSIGNALSYNCEXTPROC)(EGLDisplay dpy, EGLSync sync, const EGLAttrib * attrib_list);
typedef EGLint (GLO_API_PTR *PFNEGLCLIENTWAITSYNCPROC)(EGLDisplay dpy, EGLSync sync, EGLint flags, EGLTime timeout);
typedef EGLint (GLO_API_PTR *PFNEGLCLIENTWAITSYNCKHRPROC)(EGLDisplay dpy, EGLSyncKHR sync, EGLint flags, EGLTimeKHR timeout);
typedef EGLint (GLO_API_PTR *PFNEGLCLIENTWAITSYNCNVPROC)(EGLSyncNV sync, EGLint flags, EGLTimeNV timeout);
typedef EGLBoolean (GLO_API_PTR *PFNEGLCOMPOSITORBINDTEXWINDOWEXTPROC)(EGLint external_win_id);
typedef EGLBoolean (GLO_API_PTR *PFNEGLCOMPOSITORSETCONTEXTATTRIBUTESEXTPROC)(EGLint external_ref_id, const EGLint * context_attributes, EGLint num_entries);
typedef EGLBoolean (GLO_API_PTR *PFNEGLCOMPOSITORSETCONTEXTLISTEXTPROC)(const EGLint * external_ref_ids, EGLint num_entries);
typedef EGLBoolean (GLO_API_PTR *PFNEGLCOMPOSITORSETSIZEEXTPROC)(EGLint external_win_id, EGLint width, EGLint height);
typedef EGLBoolean (GLO_API_PTR *PFNEGLCOMPOSITORSETWINDOWATTRIBUTESEXTPROC)(EGLint external_win_id, const EGLint * window_attributes, EGLint num_entries);
typedef EGLBoolean (GLO_API_PTR *PFNEGLCOMPOSITORSETWINDOWLISTEXTPROC)(EGLint external_ref_id, const EGLint * external_win_ids, EGLint num_entries);
typedef EGLBoolean (GLO_API_PTR *PFNEGLCOMPOSITORSWAPPOLICYEXTPROC)(EGLint external_win_id, EGLint policy);
typedef EGLBoolean (GLO_API_PTR *PFNEGLCOPYBUFFERSPROC)(EGLDisplay dpy, EGLSurface surface, EGLNativePixmapType target);
typedef EGLContext (GLO_API_PTR *PFNEGLCREATECONTEXTPROC)(EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint * attrib_list);
typedef EGLImageKHR (GLO_API_PTR *PFNEGLCREATEDRMIMAGEMESAPROC)(EGLDisplay dpy, const EGLint * attrib_list);
typedef EGLSyncNV (GLO_API_PTR *PFNEGLCREATEFENCESYNCNVPROC)(EGLDisplay dpy, EGLenum condition, const EGLint * attrib_list);
typedef EGLImage (GLO_API_PTR *PFNEGLCREATEIMAGEPROC)(EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLAttrib * attrib_list);
typedef EGLImageKHR (GLO_API_PTR *PFNEGLCREATEIMAGEKHRPROC)(EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLint * attrib_list);
typedef EGLClientBuffer (GLO_API_PTR *PFNEGLCREATENATIVECLIENTBUFFERANDROIDPROC)(const EGLint * attrib_list);
typedef EGLSurface (GLO_API_PTR *PFNEGLCREATEPBUFFERFROMCLIENTBUFFERPROC)(EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint * attrib_list);
typedef EGLSurface (GLO_API_PTR *PFNEGLCREATEPBUFFERSURFACEPROC)(EGLDisplay dpy, EGLConfig config, const EGLint * attrib_list);
typedef EGLSurface (GLO_API_PTR *PFNEGLCREATEPIXMAPSURFACEPROC)(EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint * attrib_list);
typedef EGLSurface (GLO_API_PTR *PFNEGLCREATEPIXMAPSURFACEHIPROC)(EGLDisplay dpy, EGLConfig config, struct EGLClientPixmapHI * pixmap);
typedef EGLSurface (GLO_API_PTR *PFNEGLCREATEPLATFORMPIXMAPSURFACEPROC)(EGLDisplay dpy, EGLConfig config, void * native_pixmap, const EGLAttrib * attrib_list);
typedef EGLSurface (GLO_API_PTR *PFNEGLCREATEPLATFORMPIXMAPSURFACEEXTPROC)(EGLDisplay dpy, EGLConfig config, void * native_pixmap, const EGLint * attrib_list);
typedef EGLSurface (GLO_API_PTR *PFNEGLCREATEPLATFORMWINDOWSURFACEPROC)(EGLDisplay dpy, EGLConfig config, void * native_window, const EGLAttrib * attrib_list);
typedef EGLSurface (GLO_API_PTR *PFNEGLCREATEPLATFORMWINDOWSURFACEEXTPROC)(EGLDisplay dpy, EGLConfig config, void * native_window, const EGLint * attrib_list);
typedef EGLStreamKHR (GLO_API_PTR *PFNEGLCREATESTREAMATTRIBKHRPROC)(EGLDisplay dpy, const EGLAttrib * attrib_list);
typedef EGLStreamKHR (GLO_API_PTR *PFNEGLCREATESTREAMFROMFILEDESCRIPTORKHRPROC)(EGLDisplay dpy, EGLNativeFileDescriptorKHR file_descriptor);
typedef EGLStreamKHR (GLO_API_PTR *PFNEGLCREATESTREAMKHRPROC)(EGLDisplay dpy, const EGLint * attrib_list);
typedef EGLSurface (GLO_API_PTR *PFNEGLCREATESTREAMPRODUCERSURFACEKHRPROC)(EGLDisplay dpy, EGLConfig config, EGLStreamKHR stream, const EGLint * attrib_list);
typedef EGLSyncKHR (GLO_API_PTR *PFNEGLCREATESTREAMSYNCNVPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum type, const EGLint * attrib_list);
typedef EGLSync (GLO_API_PTR *PFNEGLCREATESYNCPROC)(EGLDisplay dpy, EGLenum type, const EGLAttrib * attrib_list);
typedef EGLSyncKHR (GLO_API_PTR *PFNEGLCREATESYNC64KHRPROC)(EGLDisplay dpy, EGLenum type, const EGLAttribKHR * attrib_list);
typedef EGLSyncKHR (GLO_API_PTR *PFNEGLCREATESYNCKHRPROC)(EGLDisplay dpy, EGLenum type, const EGLint * attrib_list);
typedef struct wl_buffer * (GLO_API_PTR *PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC)(EGLDisplay dpy, EGLImageKHR image);
typedef EGLSurface (GLO_API_PTR *PFNEGLCREATEWINDOWSURFACEPROC)(EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint * attrib_list);
typedef EGLint (GLO_API_PTR *PFNEGLDEBUGMESSAGECONTROLKHRPROC)(EGLDEBUGPROCKHR callback, const EGLAttrib * attrib_list);
typedef EGLBoolean (GLO_API_PTR *PFNEGLDESTROYCONTEXTPROC)(EGLDisplay dpy, EGLContext ctx);
typedef EGLBoolean (GLO_API_PTR *PFNEGLDESTROYDISPLAYEXTPROC)(EGLDisplay dpy);
typedef EGLBoolean (GLO_API_PTR *PFNEGLDESTROYIMAGEPROC)(EGLDisplay dpy, EGLImage image);
typedef EGLBoolean (GLO_API_PTR *PFNEGLDESTROYIMAGEKHRPROC)(EGLDisplay dpy, EGLImageKHR image);
typedef EGLBoolean (GLO_API_PTR *PFNEGLDESTROYSTREAMKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (GLO_API_PTR *PFNEGLDESTROYSURFACEPROC)(EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (GLO_API_PTR *PFNEGLDESTROYSYNCPROC)(EGLDisplay dpy, EGLSync sync);
typedef EGLBoolean (GLO_API_PTR *PFNEGLDESTROYSYNCKHRPROC)(EGLDisplay dpy, EGLSyncKHR sync);
typedef EGLBoolean (GLO_API_PTR *PFNEGLDESTROYSYNCNVPROC)(EGLSyncNV sync);
typedef EGLint (GLO_API_PTR *PFNEGLDUPNATIVEFENCEFDANDROIDPROC)(EGLDisplay dpy, EGLSyncKHR sync);
typedef EGLBoolean (GLO_API_PTR *PFNEGLEXPORTDMABUFIMAGEMESAPROC)(EGLDisplay dpy, EGLImageKHR image, int * fds, EGLint * strides, EGLint * offsets);
typedef EGLBoolean (GLO_API_PTR *PFNEGLEXPORTDMABUFIMAGEQUERYMESAPROC)(EGLDisplay dpy, EGLImageKHR image, int * fourcc, int * num_planes, EGLuint64KHR * modifiers);
typedef EGLBoolean (GLO_API_PTR *PFNEGLEXPORTDRMIMAGEMESAPROC)(EGLDisplay dpy, EGLImageKHR image, EGLint * name, EGLint * handle, EGLint * stride);
typedef EGLBoolean (GLO_API_PTR *PFNEGLFENCENVPROC)(EGLSyncNV sync);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETCOMPOSITORTIMINGANDROIDPROC)(EGLDisplay dpy, EGLSurface surface, EGLint numTimestamps, const EGLint * names, EGLnsecsANDROID * values);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETCOMPOSITORTIMINGSUPPORTEDANDROIDPROC)(EGLDisplay dpy, EGLSurface surface, EGLint name);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETCONFIGATTRIBPROC)(EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETCONFIGSPROC)(EGLDisplay dpy, EGLConfig * configs, EGLint config_size, EGLint * num_config);
typedef EGLContext (GLO_API_PTR *PFNEGLGETCURRENTCONTEXTPROC)(void);
typedef EGLDisplay (GLO_API_PTR *PFNEGLGETCURRENTDISPLAYPROC)(void);
typedef EGLSurface (GLO_API_PTR *PFNEGLGETCURRENTSURFACEPROC)(EGLint readdraw);
typedef EGLDisplay (GLO_API_PTR *PFNEGLGETDISPLAYPROC)(EGLNativeDisplayType display_id);
typedef char * (GLO_API_PTR *PFNEGLGETDISPLAYDRIVERCONFIGPROC)(EGLDisplay dpy);
typedef const char * (GLO_API_PTR *PFNEGLGETDISPLAYDRIVERNAMEPROC)(EGLDisplay dpy);
typedef EGLint (GLO_API_PTR *PFNEGLGETERRORPROC)(void);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETFRAMETIMESTAMPSUPPORTEDANDROIDPROC)(EGLDisplay dpy, EGLSurface surface, EGLint timestamp);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETFRAMETIMESTAMPSANDROIDPROC)(EGLDisplay dpy, EGLSurface surface, EGLuint64KHR frameId, EGLint numTimestamps, const EGLint * timestamps, EGLnsecsANDROID * values);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETMSCRATEANGLEPROC)(EGLDisplay dpy, EGLSurface surface, EGLint * numerator, EGLint * denominator);
typedef EGLClientBuffer (GLO_API_PTR *PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC)(const struct AHardwareBuffer * buffer);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETNEXTFRAMEIDANDROIDPROC)(EGLDisplay dpy, EGLSurface surface, EGLuint64KHR * frameId);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETOUTPUTLAYERSEXTPROC)(EGLDisplay dpy, const EGLAttrib * attrib_list, EGLOutputLayerEXT * layers, EGLint max_layers, EGLint * num_layers);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETOUTPUTPORTSEXTPROC)(EGLDisplay dpy, const EGLAttrib * attrib_list, EGLOutputPortEXT * ports, EGLint max_ports, EGLint * num_ports);
typedef EGLDisplay (GLO_API_PTR *PFNEGLGETPLATFORMDISPLAYPROC)(EGLenum platform, void * native_display, const EGLAttrib * attrib_list);
typedef EGLDisplay (GLO_API_PTR *PFNEGLGETPLATFORMDISPLAYEXTPROC)(EGLenum platform, void * native_display, const EGLint * attrib_list);
typedef __eglMustCastToProperFunctionPointerType (GLO_API_PTR *PFNEGLGETPROCADDRESSPROC)(const char * procname);
typedef EGLNativeFileDescriptorKHR (GLO_API_PTR *PFNEGLGETSTREAMFILEDESCRIPTORKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETSYNCATTRIBPROC)(EGLDisplay dpy, EGLSync sync, EGLint attribute, EGLAttrib * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETSYNCATTRIBKHRPROC)(EGLDisplay dpy, EGLSyncKHR sync, EGLint attribute, EGLint * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLGETSYNCATTRIBNVPROC)(EGLSyncNV sync, EGLint attribute, EGLint * value);
typedef EGLuint64NV (GLO_API_PTR *PFNEGLGETSYSTEMTIMEFREQUENCYNVPROC)(void);
typedef EGLuint64NV (GLO_API_PTR *PFNEGLGETSYSTEMTIMENVPROC)(void);
typedef EGLBoolean (GLO_API_PTR *PFNEGLINITIALIZEPROC)(EGLDisplay dpy, EGLint * major, EGLint * minor);
typedef EGLint (GLO_API_PTR *PFNEGLLABELOBJECTKHRPROC)(EGLDisplay display, EGLenum objectType, EGLObjectKHR object, EGLLabelKHR label);
typedef EGLBoolean (GLO_API_PTR *PFNEGLLOCKSURFACEKHRPROC)(EGLDisplay dpy, EGLSurface surface, const EGLint * attrib_list);
typedef EGLBoolean (GLO_API_PTR *PFNEGLMAKECURRENTPROC)(EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx);
typedef EGLBoolean (GLO_API_PTR *PFNEGLOUTPUTLAYERATTRIBEXTPROC)(EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint attribute, EGLAttrib value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLOUTPUTPORTATTRIBEXTPROC)(EGLDisplay dpy, EGLOutputPortEXT port, EGLint attribute, EGLAttrib value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLPOSTSUBBUFFERNVPROC)(EGLDisplay dpy, EGLSurface surface, EGLint x, EGLint y, EGLint width, EGLint height);
typedef EGLBoolean (GLO_API_PTR *PFNEGLPRESENTATIONTIMEANDROIDPROC)(EGLDisplay dpy, EGLSurface surface, EGLnsecsANDROID time);
typedef EGLenum (GLO_API_PTR *PFNEGLQUERYAPIPROC)(void);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYCONTEXTPROC)(EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYDEBUGKHRPROC)(EGLint attribute, EGLAttrib * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYDEVICEATTRIBEXTPROC)(EGLDeviceEXT device, EGLint attribute, EGLAttrib * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYDEVICEBINARYEXTPROC)(EGLDeviceEXT device, EGLint name, EGLint max_size, void * value, EGLint * size);
typedef const char * (GLO_API_PTR *PFNEGLQUERYDEVICESTRINGEXTPROC)(EGLDeviceEXT device, EGLint name);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYDEVICESEXTPROC)(EGLint max_devices, EGLDeviceEXT * devices, EGLint * num_devices);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYDISPLAYATTRIBEXTPROC)(EGLDisplay dpy, EGLint attribute, EGLAttrib * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYDISPLAYATTRIBKHRPROC)(EGLDisplay dpy, EGLint name, EGLAttrib * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYDISPLAYATTRIBNVPROC)(EGLDisplay dpy, EGLint attribute, EGLAttrib * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYDMABUFFORMATSEXTPROC)(EGLDisplay dpy, EGLint max_formats, EGLint * formats, EGLint * num_formats);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYDMABUFMODIFIERSEXTPROC)(EGLDisplay dpy, EGLint format, EGLint max_modifiers, EGLuint64KHR * modifiers, EGLBoolean * external_only, EGLint * num_modifiers);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYNATIVEDISPLAYNVPROC)(EGLDisplay dpy, EGLNativeDisplayType * display_id);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYNATIVEPIXMAPNVPROC)(EGLDisplay dpy, EGLSurface surf, EGLNativePixmapType * pixmap);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYNATIVEWINDOWNVPROC)(EGLDisplay dpy, EGLSurface surf, EGLNativeWindowType * window);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYOUTPUTLAYERATTRIBEXTPROC)(EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint attribute, EGLAttrib * value);
typedef const char * (GLO_API_PTR *PFNEGLQUERYOUTPUTLAYERSTRINGEXTPROC)(EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint name);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYOUTPUTPORTATTRIBEXTPROC)(EGLDisplay dpy, EGLOutputPortEXT port, EGLint attribute, EGLAttrib * value);
typedef const char * (GLO_API_PTR *PFNEGLQUERYOUTPUTPORTSTRINGEXTPROC)(EGLDisplay dpy, EGLOutputPortEXT port, EGLint name);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYSTREAMATTRIBKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLAttrib * value);
typedef EGLint (GLO_API_PTR *PFNEGLQUERYSTREAMCONSUMEREVENTNVPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLTime timeout, EGLenum * event, EGLAttrib * aux);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYSTREAMKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLint * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYSTREAMMETADATANVPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum name, EGLint n, EGLint offset, EGLint size, void * data);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYSTREAMTIMEKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLTimeKHR * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYSTREAMU64KHRPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLuint64KHR * value);
typedef const char * (GLO_API_PTR *PFNEGLQUERYSTRINGPROC)(EGLDisplay dpy, EGLint name);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYSUPPORTEDCOMPRESSIONRATESEXTPROC)(EGLDisplay dpy, EGLConfig config, const EGLAttrib * attrib_list, EGLint * rates, EGLint rate_size, EGLint * num_rates);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYSURFACEPROC)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYSURFACE64KHRPROC)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLAttribKHR * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYSURFACEPOINTERANGLEPROC)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, void ** value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLQUERYWAYLANDBUFFERWLPROC)(EGLDisplay dpy, struct wl_resource * buffer, EGLint attribute, EGLint * value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLRELEASETEXIMAGEPROC)(EGLDisplay dpy, EGLSurface surface, EGLint buffer);
typedef EGLBoolean (GLO_API_PTR *PFNEGLRELEASETHREADPROC)(void);
typedef EGLBoolean (GLO_API_PTR *PFNEGLRESETSTREAMNVPROC)(EGLDisplay dpy, EGLStreamKHR stream);
typedef void (GLO_API_PTR *PFNEGLSETBLOBCACHEFUNCSANDROIDPROC)(EGLDisplay dpy, EGLSetBlobFuncANDROID set, EGLGetBlobFuncANDROID get);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSETDAMAGEREGIONKHRPROC)(EGLDisplay dpy, EGLSurface surface, EGLint * rects, EGLint n_rects);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSETSTREAMATTRIBKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLAttrib value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSETSTREAMMETADATANVPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLint n, EGLint offset, EGLint size, const void * data);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSIGNALSYNCKHRPROC)(EGLDisplay dpy, EGLSyncKHR sync, EGLenum mode);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSIGNALSYNCNVPROC)(EGLSyncNV sync, EGLenum mode);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMACQUIREIMAGENVPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLImage * pImage, EGLSync sync);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMATTRIBKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLint value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMCONSUMERACQUIREATTRIBKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib * attrib_list);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMCONSUMERACQUIREKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALATTRIBSNVPROC)(EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib * attrib_list);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMCONSUMEROUTPUTEXTPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLOutputLayerEXT layer);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMCONSUMERRELEASEATTRIBKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib * attrib_list);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMCONSUMERRELEASEKHRPROC)(EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMFLUSHNVPROC)(EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMIMAGECONSUMERCONNECTNVPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLint num_modifiers, const EGLuint64KHR * modifiers, const EGLAttrib * attrib_list);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSTREAMRELEASEIMAGENVPROC)(EGLDisplay dpy, EGLStreamKHR stream, EGLImage image, EGLSync sync);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSURFACEATTRIBPROC)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint value);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSWAPBUFFERSPROC)(EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSWAPBUFFERSREGION2NOKPROC)(EGLDisplay dpy, EGLSurface surface, EGLint numRects, const EGLint * rects);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSWAPBUFFERSREGIONNOKPROC)(EGLDisplay dpy, EGLSurface surface, EGLint numRects, const EGLint * rects);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSWAPBUFFERSWITHDAMAGEEXTPROC)(EGLDisplay dpy, EGLSurface surface, const EGLint * rects, EGLint n_rects);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSWAPBUFFERSWITHDAMAGEKHRPROC)(EGLDisplay dpy, EGLSurface surface, const EGLint * rects, EGLint n_rects);
typedef EGLBoolean (GLO_API_PTR *PFNEGLSWAPINTERVALPROC)(EGLDisplay dpy, EGLint interval);
typedef EGLBoolean (GLO_API_PTR *PFNEGLTERMINATEPROC)(EGLDisplay dpy);
typedef EGLBoolean (GLO_API_PTR *PFNEGLUNBINDWAYLANDDISPLAYWLPROC)(EGLDisplay dpy, struct wl_display * display);
typedef EGLBoolean (GLO_API_PTR *PFNEGLUNLOCKSURFACEKHRPROC)(EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (GLO_API_PTR *PFNEGLUNSIGNALSYNCEXTPROC)(EGLDisplay dpy, EGLSync sync, const EGLAttrib * attrib_list);
typedef EGLBoolean (GLO_API_PTR *PFNEGLWAITCLIENTPROC)(void);
typedef EGLBoolean (GLO_API_PTR *PFNEGLWAITGLPROC)(void);
typedef EGLBoolean (GLO_API_PTR *PFNEGLWAITNATIVEPROC)(EGLint engine);
typedef EGLBoolean (GLO_API_PTR *PFNEGLWAITSYNCPROC)(EGLDisplay dpy, EGLSync sync, EGLint flags);
typedef EGLint (GLO_API_PTR *PFNEGLWAITSYNCKHRPROC)(EGLDisplay dpy, EGLSyncKHR sync, EGLint flags);

GLO_API_CALL PFNEGLBINDAPIPROC glo_eglBindAPI;
#define eglBindAPI glo_eglBindAPI
GLO_API_CALL PFNEGLBINDTEXIMAGEPROC glo_eglBindTexImage;
#define eglBindTexImage glo_eglBindTexImage
GLO_API_CALL PFNEGLBINDWAYLANDDISPLAYWLPROC glo_eglBindWaylandDisplayWL;
#define eglBindWaylandDisplayWL glo_eglBindWaylandDisplayWL
GLO_API_CALL PFNEGLCHOOSECONFIGPROC glo_eglChooseConfig;
#define eglChooseConfig glo_eglChooseConfig
GLO_API_CALL PFNEGLCLIENTSIGNALSYNCEXTPROC glo_eglClientSignalSyncEXT;
#define eglClientSignalSyncEXT glo_eglClientSignalSyncEXT
GLO_API_CALL PFNEGLCLIENTWAITSYNCPROC glo_eglClientWaitSync;
#define eglClientWaitSync glo_eglClientWaitSync
GLO_API_CALL PFNEGLCLIENTWAITSYNCKHRPROC glo_eglClientWaitSyncKHR;
#define eglClientWaitSyncKHR glo_eglClientWaitSyncKHR
GLO_API_CALL PFNEGLCLIENTWAITSYNCNVPROC glo_eglClientWaitSyncNV;
#define eglClientWaitSyncNV glo_eglClientWaitSyncNV
GLO_API_CALL PFNEGLCOMPOSITORBINDTEXWINDOWEXTPROC glo_eglCompositorBindTexWindowEXT;
#define eglCompositorBindTexWindowEXT glo_eglCompositorBindTexWindowEXT
GLO_API_CALL PFNEGLCOMPOSITORSETCONTEXTATTRIBUTESEXTPROC glo_eglCompositorSetContextAttributesEXT;
#define eglCompositorSetContextAttributesEXT glo_eglCompositorSetContextAttributesEXT
GLO_API_CALL PFNEGLCOMPOSITORSETCONTEXTLISTEXTPROC glo_eglCompositorSetContextListEXT;
#define eglCompositorSetContextListEXT glo_eglCompositorSetContextListEXT
GLO_API_CALL PFNEGLCOMPOSITORSETSIZEEXTPROC glo_eglCompositorSetSizeEXT;
#define eglCompositorSetSizeEXT glo_eglCompositorSetSizeEXT
GLO_API_CALL PFNEGLCOMPOSITORSETWINDOWATTRIBUTESEXTPROC glo_eglCompositorSetWindowAttributesEXT;
#define eglCompositorSetWindowAttributesEXT glo_eglCompositorSetWindowAttributesEXT
GLO_API_CALL PFNEGLCOMPOSITORSETWINDOWLISTEXTPROC glo_eglCompositorSetWindowListEXT;
#define eglCompositorSetWindowListEXT glo_eglCompositorSetWindowListEXT
GLO_API_CALL PFNEGLCOMPOSITORSWAPPOLICYEXTPROC glo_eglCompositorSwapPolicyEXT;
#define eglCompositorSwapPolicyEXT glo_eglCompositorSwapPolicyEXT
GLO_API_CALL PFNEGLCOPYBUFFERSPROC glo_eglCopyBuffers;
#define eglCopyBuffers glo_eglCopyBuffers
GLO_API_CALL PFNEGLCREATECONTEXTPROC glo_eglCreateContext;
#define eglCreateContext glo_eglCreateContext
GLO_API_CALL PFNEGLCREATEDRMIMAGEMESAPROC glo_eglCreateDRMImageMESA;
#define eglCreateDRMImageMESA glo_eglCreateDRMImageMESA
GLO_API_CALL PFNEGLCREATEFENCESYNCNVPROC glo_eglCreateFenceSyncNV;
#define eglCreateFenceSyncNV glo_eglCreateFenceSyncNV
GLO_API_CALL PFNEGLCREATEIMAGEPROC glo_eglCreateImage;
#define eglCreateImage glo_eglCreateImage
GLO_API_CALL PFNEGLCREATEIMAGEKHRPROC glo_eglCreateImageKHR;
#define eglCreateImageKHR glo_eglCreateImageKHR
GLO_API_CALL PFNEGLCREATENATIVECLIENTBUFFERANDROIDPROC glo_eglCreateNativeClientBufferANDROID;
#define eglCreateNativeClientBufferANDROID glo_eglCreateNativeClientBufferANDROID
GLO_API_CALL PFNEGLCREATEPBUFFERFROMCLIENTBUFFERPROC glo_eglCreatePbufferFromClientBuffer;
#define eglCreatePbufferFromClientBuffer glo_eglCreatePbufferFromClientBuffer
GLO_API_CALL PFNEGLCREATEPBUFFERSURFACEPROC glo_eglCreatePbufferSurface;
#define eglCreatePbufferSurface glo_eglCreatePbufferSurface
GLO_API_CALL PFNEGLCREATEPIXMAPSURFACEPROC glo_eglCreatePixmapSurface;
#define eglCreatePixmapSurface glo_eglCreatePixmapSurface
GLO_API_CALL PFNEGLCREATEPIXMAPSURFACEHIPROC glo_eglCreatePixmapSurfaceHI;
#define eglCreatePixmapSurfaceHI glo_eglCreatePixmapSurfaceHI
GLO_API_CALL PFNEGLCREATEPLATFORMPIXMAPSURFACEPROC glo_eglCreatePlatformPixmapSurface;
#define eglCreatePlatformPixmapSurface glo_eglCreatePlatformPixmapSurface
GLO_API_CALL PFNEGLCREATEPLATFORMPIXMAPSURFACEEXTPROC glo_eglCreatePlatformPixmapSurfaceEXT;
#define eglCreatePlatformPixmapSurfaceEXT glo_eglCreatePlatformPixmapSurfaceEXT
GLO_API_CALL PFNEGLCREATEPLATFORMWINDOWSURFACEPROC glo_eglCreatePlatformWindowSurface;
#define eglCreatePlatformWindowSurface glo_eglCreatePlatformWindowSurface
GLO_API_CALL PFNEGLCREATEPLATFORMWINDOWSURFACEEXTPROC glo_eglCreatePlatformWindowSurfaceEXT;
#define eglCreatePlatformWindowSurfaceEXT glo_eglCreatePlatformWindowSurfaceEXT
GLO_API_CALL PFNEGLCREATESTREAMATTRIBKHRPROC glo_eglCreateStreamAttribKHR;
#define eglCreateStreamAttribKHR glo_eglCreateStreamAttribKHR
GLO_API_CALL PFNEGLCREATESTREAMFROMFILEDESCRIPTORKHRPROC glo_eglCreateStreamFromFileDescriptorKHR;
#define eglCreateStreamFromFileDescriptorKHR glo_eglCreateStreamFromFileDescriptorKHR
GLO_API_CALL PFNEGLCREATESTREAMKHRPROC glo_eglCreateStreamKHR;
#define eglCreateStreamKHR glo_eglCreateStreamKHR
GLO_API_CALL PFNEGLCREATESTREAMPRODUCERSURFACEKHRPROC glo_eglCreateStreamProducerSurfaceKHR;
#define eglCreateStreamProducerSurfaceKHR glo_eglCreateStreamProducerSurfaceKHR
GLO_API_CALL PFNEGLCREATESTREAMSYNCNVPROC glo_eglCreateStreamSyncNV;
#define eglCreateStreamSyncNV glo_eglCreateStreamSyncNV
GLO_API_CALL PFNEGLCREATESYNCPROC glo_eglCreateSync;
#define eglCreateSync glo_eglCreateSync
GLO_API_CALL PFNEGLCREATESYNC64KHRPROC glo_eglCreateSync64KHR;
#define eglCreateSync64KHR glo_eglCreateSync64KHR
GLO_API_CALL PFNEGLCREATESYNCKHRPROC glo_eglCreateSyncKHR;
#define eglCreateSyncKHR glo_eglCreateSyncKHR
GLO_API_CALL PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC glo_eglCreateWaylandBufferFromImageWL;
#define eglCreateWaylandBufferFromImageWL glo_eglCreateWaylandBufferFromImageWL
GLO_API_CALL PFNEGLCREATEWINDOWSURFACEPROC glo_eglCreateWindowSurface;
#define eglCreateWindowSurface glo_eglCreateWindowSurface
GLO_API_CALL PFNEGLDEBUGMESSAGECONTROLKHRPROC glo_eglDebugMessageControlKHR;
#define eglDebugMessageControlKHR glo_eglDebugMessageControlKHR
GLO_API_CALL PFNEGLDESTROYCONTEXTPROC glo_eglDestroyContext;
#define eglDestroyContext glo_eglDestroyContext
GLO_API_CALL PFNEGLDESTROYDISPLAYEXTPROC glo_eglDestroyDisplayEXT;
#define eglDestroyDisplayEXT glo_eglDestroyDisplayEXT
GLO_API_CALL PFNEGLDESTROYIMAGEPROC glo_eglDestroyImage;
#define eglDestroyImage glo_eglDestroyImage
GLO_API_CALL PFNEGLDESTROYIMAGEKHRPROC glo_eglDestroyImageKHR;
#define eglDestroyImageKHR glo_eglDestroyImageKHR
GLO_API_CALL PFNEGLDESTROYSTREAMKHRPROC glo_eglDestroyStreamKHR;
#define eglDestroyStreamKHR glo_eglDestroyStreamKHR
GLO_API_CALL PFNEGLDESTROYSURFACEPROC glo_eglDestroySurface;
#define eglDestroySurface glo_eglDestroySurface
GLO_API_CALL PFNEGLDESTROYSYNCPROC glo_eglDestroySync;
#define eglDestroySync glo_eglDestroySync
GLO_API_CALL PFNEGLDESTROYSYNCKHRPROC glo_eglDestroySyncKHR;
#define eglDestroySyncKHR glo_eglDestroySyncKHR
GLO_API_CALL PFNEGLDESTROYSYNCNVPROC glo_eglDestroySyncNV;
#define eglDestroySyncNV glo_eglDestroySyncNV
GLO_API_CALL PFNEGLDUPNATIVEFENCEFDANDROIDPROC glo_eglDupNativeFenceFDANDROID;
#define eglDupNativeFenceFDANDROID glo_eglDupNativeFenceFDANDROID
GLO_API_CALL PFNEGLEXPORTDMABUFIMAGEMESAPROC glo_eglExportDMABUFImageMESA;
#define eglExportDMABUFImageMESA glo_eglExportDMABUFImageMESA
GLO_API_CALL PFNEGLEXPORTDMABUFIMAGEQUERYMESAPROC glo_eglExportDMABUFImageQueryMESA;
#define eglExportDMABUFImageQueryMESA glo_eglExportDMABUFImageQueryMESA
GLO_API_CALL PFNEGLEXPORTDRMIMAGEMESAPROC glo_eglExportDRMImageMESA;
#define eglExportDRMImageMESA glo_eglExportDRMImageMESA
GLO_API_CALL PFNEGLFENCENVPROC glo_eglFenceNV;
#define eglFenceNV glo_eglFenceNV
GLO_API_CALL PFNEGLGETCOMPOSITORTIMINGANDROIDPROC glo_eglGetCompositorTimingANDROID;
#define eglGetCompositorTimingANDROID glo_eglGetCompositorTimingANDROID
GLO_API_CALL PFNEGLGETCOMPOSITORTIMINGSUPPORTEDANDROIDPROC glo_eglGetCompositorTimingSupportedANDROID;
#define eglGetCompositorTimingSupportedANDROID glo_eglGetCompositorTimingSupportedANDROID
GLO_API_CALL PFNEGLGETCONFIGATTRIBPROC glo_eglGetConfigAttrib;
#define eglGetConfigAttrib glo_eglGetConfigAttrib
GLO_API_CALL PFNEGLGETCONFIGSPROC glo_eglGetConfigs;
#define eglGetConfigs glo_eglGetConfigs
GLO_API_CALL PFNEGLGETCURRENTCONTEXTPROC glo_eglGetCurrentContext;
#define eglGetCurrentContext glo_eglGetCurrentContext
GLO_API_CALL PFNEGLGETCURRENTDISPLAYPROC glo_eglGetCurrentDisplay;
#define eglGetCurrentDisplay glo_eglGetCurrentDisplay
GLO_API_CALL PFNEGLGETCURRENTSURFACEPROC glo_eglGetCurrentSurface;
#define eglGetCurrentSurface glo_eglGetCurrentSurface
GLO_API_CALL PFNEGLGETDISPLAYPROC glo_eglGetDisplay;
#define eglGetDisplay glo_eglGetDisplay
GLO_API_CALL PFNEGLGETDISPLAYDRIVERCONFIGPROC glo_eglGetDisplayDriverConfig;
#define eglGetDisplayDriverConfig glo_eglGetDisplayDriverConfig
GLO_API_CALL PFNEGLGETDISPLAYDRIVERNAMEPROC glo_eglGetDisplayDriverName;
#define eglGetDisplayDriverName glo_eglGetDisplayDriverName
GLO_API_CALL PFNEGLGETERRORPROC glo_eglGetError;
#define eglGetError glo_eglGetError
GLO_API_CALL PFNEGLGETFRAMETIMESTAMPSUPPORTEDANDROIDPROC glo_eglGetFrameTimestampSupportedANDROID;
#define eglGetFrameTimestampSupportedANDROID glo_eglGetFrameTimestampSupportedANDROID
GLO_API_CALL PFNEGLGETFRAMETIMESTAMPSANDROIDPROC glo_eglGetFrameTimestampsANDROID;
#define eglGetFrameTimestampsANDROID glo_eglGetFrameTimestampsANDROID
GLO_API_CALL PFNEGLGETMSCRATEANGLEPROC glo_eglGetMscRateANGLE;
#define eglGetMscRateANGLE glo_eglGetMscRateANGLE
GLO_API_CALL PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC glo_eglGetNativeClientBufferANDROID;
#define eglGetNativeClientBufferANDROID glo_eglGetNativeClientBufferANDROID
GLO_API_CALL PFNEGLGETNEXTFRAMEIDANDROIDPROC glo_eglGetNextFrameIdANDROID;
#define eglGetNextFrameIdANDROID glo_eglGetNextFrameIdANDROID
GLO_API_CALL PFNEGLGETOUTPUTLAYERSEXTPROC glo_eglGetOutputLayersEXT;
#define eglGetOutputLayersEXT glo_eglGetOutputLayersEXT
GLO_API_CALL PFNEGLGETOUTPUTPORTSEXTPROC glo_eglGetOutputPortsEXT;
#define eglGetOutputPortsEXT glo_eglGetOutputPortsEXT
GLO_API_CALL PFNEGLGETPLATFORMDISPLAYPROC glo_eglGetPlatformDisplay;
#define eglGetPlatformDisplay glo_eglGetPlatformDisplay
GLO_API_CALL PFNEGLGETPLATFORMDISPLAYEXTPROC glo_eglGetPlatformDisplayEXT;
#define eglGetPlatformDisplayEXT glo_eglGetPlatformDisplayEXT
GLO_API_CALL PFNEGLGETPROCADDRESSPROC glo_eglGetProcAddress;
#define eglGetProcAddress glo_eglGetProcAddress
GLO_API_CALL PFNEGLGETSTREAMFILEDESCRIPTORKHRPROC glo_eglGetStreamFileDescriptorKHR;
#define eglGetStreamFileDescriptorKHR glo_eglGetStreamFileDescriptorKHR
GLO_API_CALL PFNEGLGETSYNCATTRIBPROC glo_eglGetSyncAttrib;
#define eglGetSyncAttrib glo_eglGetSyncAttrib
GLO_API_CALL PFNEGLGETSYNCATTRIBKHRPROC glo_eglGetSyncAttribKHR;
#define eglGetSyncAttribKHR glo_eglGetSyncAttribKHR
GLO_API_CALL PFNEGLGETSYNCATTRIBNVPROC glo_eglGetSyncAttribNV;
#define eglGetSyncAttribNV glo_eglGetSyncAttribNV
GLO_API_CALL PFNEGLGETSYSTEMTIMEFREQUENCYNVPROC glo_eglGetSystemTimeFrequencyNV;
#define eglGetSystemTimeFrequencyNV glo_eglGetSystemTimeFrequencyNV
GLO_API_CALL PFNEGLGETSYSTEMTIMENVPROC glo_eglGetSystemTimeNV;
#define eglGetSystemTimeNV glo_eglGetSystemTimeNV
GLO_API_CALL PFNEGLINITIALIZEPROC glo_eglInitialize;
#define eglInitialize glo_eglInitialize
GLO_API_CALL PFNEGLLABELOBJECTKHRPROC glo_eglLabelObjectKHR;
#define eglLabelObjectKHR glo_eglLabelObjectKHR
GLO_API_CALL PFNEGLLOCKSURFACEKHRPROC glo_eglLockSurfaceKHR;
#define eglLockSurfaceKHR glo_eglLockSurfaceKHR
GLO_API_CALL PFNEGLMAKECURRENTPROC glo_eglMakeCurrent;
#define eglMakeCurrent glo_eglMakeCurrent
GLO_API_CALL PFNEGLOUTPUTLAYERATTRIBEXTPROC glo_eglOutputLayerAttribEXT;
#define eglOutputLayerAttribEXT glo_eglOutputLayerAttribEXT
GLO_API_CALL PFNEGLOUTPUTPORTATTRIBEXTPROC glo_eglOutputPortAttribEXT;
#define eglOutputPortAttribEXT glo_eglOutputPortAttribEXT
GLO_API_CALL PFNEGLPOSTSUBBUFFERNVPROC glo_eglPostSubBufferNV;
#define eglPostSubBufferNV glo_eglPostSubBufferNV
GLO_API_CALL PFNEGLPRESENTATIONTIMEANDROIDPROC glo_eglPresentationTimeANDROID;
#define eglPresentationTimeANDROID glo_eglPresentationTimeANDROID
GLO_API_CALL PFNEGLQUERYAPIPROC glo_eglQueryAPI;
#define eglQueryAPI glo_eglQueryAPI
GLO_API_CALL PFNEGLQUERYCONTEXTPROC glo_eglQueryContext;
#define eglQueryContext glo_eglQueryContext
GLO_API_CALL PFNEGLQUERYDEBUGKHRPROC glo_eglQueryDebugKHR;
#define eglQueryDebugKHR glo_eglQueryDebugKHR
GLO_API_CALL PFNEGLQUERYDEVICEATTRIBEXTPROC glo_eglQueryDeviceAttribEXT;
#define eglQueryDeviceAttribEXT glo_eglQueryDeviceAttribEXT
GLO_API_CALL PFNEGLQUERYDEVICEBINARYEXTPROC glo_eglQueryDeviceBinaryEXT;
#define eglQueryDeviceBinaryEXT glo_eglQueryDeviceBinaryEXT
GLO_API_CALL PFNEGLQUERYDEVICESTRINGEXTPROC glo_eglQueryDeviceStringEXT;
#define eglQueryDeviceStringEXT glo_eglQueryDeviceStringEXT
GLO_API_CALL PFNEGLQUERYDEVICESEXTPROC glo_eglQueryDevicesEXT;
#define eglQueryDevicesEXT glo_eglQueryDevicesEXT
GLO_API_CALL PFNEGLQUERYDISPLAYATTRIBEXTPROC glo_eglQueryDisplayAttribEXT;
#define eglQueryDisplayAttribEXT glo_eglQueryDisplayAttribEXT
GLO_API_CALL PFNEGLQUERYDISPLAYATTRIBKHRPROC glo_eglQueryDisplayAttribKHR;
#define eglQueryDisplayAttribKHR glo_eglQueryDisplayAttribKHR
GLO_API_CALL PFNEGLQUERYDISPLAYATTRIBNVPROC glo_eglQueryDisplayAttribNV;
#define eglQueryDisplayAttribNV glo_eglQueryDisplayAttribNV
GLO_API_CALL PFNEGLQUERYDMABUFFORMATSEXTPROC glo_eglQueryDmaBufFormatsEXT;
#define eglQueryDmaBufFormatsEXT glo_eglQueryDmaBufFormatsEXT
GLO_API_CALL PFNEGLQUERYDMABUFMODIFIERSEXTPROC glo_eglQueryDmaBufModifiersEXT;
#define eglQueryDmaBufModifiersEXT glo_eglQueryDmaBufModifiersEXT
GLO_API_CALL PFNEGLQUERYNATIVEDISPLAYNVPROC glo_eglQueryNativeDisplayNV;
#define eglQueryNativeDisplayNV glo_eglQueryNativeDisplayNV
GLO_API_CALL PFNEGLQUERYNATIVEPIXMAPNVPROC glo_eglQueryNativePixmapNV;
#define eglQueryNativePixmapNV glo_eglQueryNativePixmapNV
GLO_API_CALL PFNEGLQUERYNATIVEWINDOWNVPROC glo_eglQueryNativeWindowNV;
#define eglQueryNativeWindowNV glo_eglQueryNativeWindowNV
GLO_API_CALL PFNEGLQUERYOUTPUTLAYERATTRIBEXTPROC glo_eglQueryOutputLayerAttribEXT;
#define eglQueryOutputLayerAttribEXT glo_eglQueryOutputLayerAttribEXT
GLO_API_CALL PFNEGLQUERYOUTPUTLAYERSTRINGEXTPROC glo_eglQueryOutputLayerStringEXT;
#define eglQueryOutputLayerStringEXT glo_eglQueryOutputLayerStringEXT
GLO_API_CALL PFNEGLQUERYOUTPUTPORTATTRIBEXTPROC glo_eglQueryOutputPortAttribEXT;
#define eglQueryOutputPortAttribEXT glo_eglQueryOutputPortAttribEXT
GLO_API_CALL PFNEGLQUERYOUTPUTPORTSTRINGEXTPROC glo_eglQueryOutputPortStringEXT;
#define eglQueryOutputPortStringEXT glo_eglQueryOutputPortStringEXT
GLO_API_CALL PFNEGLQUERYSTREAMATTRIBKHRPROC glo_eglQueryStreamAttribKHR;
#define eglQueryStreamAttribKHR glo_eglQueryStreamAttribKHR
GLO_API_CALL PFNEGLQUERYSTREAMCONSUMEREVENTNVPROC glo_eglQueryStreamConsumerEventNV;
#define eglQueryStreamConsumerEventNV glo_eglQueryStreamConsumerEventNV
GLO_API_CALL PFNEGLQUERYSTREAMKHRPROC glo_eglQueryStreamKHR;
#define eglQueryStreamKHR glo_eglQueryStreamKHR
GLO_API_CALL PFNEGLQUERYSTREAMMETADATANVPROC glo_eglQueryStreamMetadataNV;
#define eglQueryStreamMetadataNV glo_eglQueryStreamMetadataNV
GLO_API_CALL PFNEGLQUERYSTREAMTIMEKHRPROC glo_eglQueryStreamTimeKHR;
#define eglQueryStreamTimeKHR glo_eglQueryStreamTimeKHR
GLO_API_CALL PFNEGLQUERYSTREAMU64KHRPROC glo_eglQueryStreamu64KHR;
#define eglQueryStreamu64KHR glo_eglQueryStreamu64KHR
GLO_API_CALL PFNEGLQUERYSTRINGPROC glo_eglQueryString;
#define eglQueryString glo_eglQueryString
GLO_API_CALL PFNEGLQUERYSUPPORTEDCOMPRESSIONRATESEXTPROC glo_eglQuerySupportedCompressionRatesEXT;
#define eglQuerySupportedCompressionRatesEXT glo_eglQuerySupportedCompressionRatesEXT
GLO_API_CALL PFNEGLQUERYSURFACEPROC glo_eglQuerySurface;
#define eglQuerySurface glo_eglQuerySurface
GLO_API_CALL PFNEGLQUERYSURFACE64KHRPROC glo_eglQuerySurface64KHR;
#define eglQuerySurface64KHR glo_eglQuerySurface64KHR
GLO_API_CALL PFNEGLQUERYSURFACEPOINTERANGLEPROC glo_eglQuerySurfacePointerANGLE;
#define eglQuerySurfacePointerANGLE glo_eglQuerySurfacePointerANGLE
GLO_API_CALL PFNEGLQUERYWAYLANDBUFFERWLPROC glo_eglQueryWaylandBufferWL;
#define eglQueryWaylandBufferWL glo_eglQueryWaylandBufferWL
GLO_API_CALL PFNEGLRELEASETEXIMAGEPROC glo_eglReleaseTexImage;
#define eglReleaseTexImage glo_eglReleaseTexImage
GLO_API_CALL PFNEGLRELEASETHREADPROC glo_eglReleaseThread;
#define eglReleaseThread glo_eglReleaseThread
GLO_API_CALL PFNEGLRESETSTREAMNVPROC glo_eglResetStreamNV;
#define eglResetStreamNV glo_eglResetStreamNV
GLO_API_CALL PFNEGLSETBLOBCACHEFUNCSANDROIDPROC glo_eglSetBlobCacheFuncsANDROID;
#define eglSetBlobCacheFuncsANDROID glo_eglSetBlobCacheFuncsANDROID
GLO_API_CALL PFNEGLSETDAMAGEREGIONKHRPROC glo_eglSetDamageRegionKHR;
#define eglSetDamageRegionKHR glo_eglSetDamageRegionKHR
GLO_API_CALL PFNEGLSETSTREAMATTRIBKHRPROC glo_eglSetStreamAttribKHR;
#define eglSetStreamAttribKHR glo_eglSetStreamAttribKHR
GLO_API_CALL PFNEGLSETSTREAMMETADATANVPROC glo_eglSetStreamMetadataNV;
#define eglSetStreamMetadataNV glo_eglSetStreamMetadataNV
GLO_API_CALL PFNEGLSIGNALSYNCKHRPROC glo_eglSignalSyncKHR;
#define eglSignalSyncKHR glo_eglSignalSyncKHR
GLO_API_CALL PFNEGLSIGNALSYNCNVPROC glo_eglSignalSyncNV;
#define eglSignalSyncNV glo_eglSignalSyncNV
GLO_API_CALL PFNEGLSTREAMACQUIREIMAGENVPROC glo_eglStreamAcquireImageNV;
#define eglStreamAcquireImageNV glo_eglStreamAcquireImageNV
GLO_API_CALL PFNEGLSTREAMATTRIBKHRPROC glo_eglStreamAttribKHR;
#define eglStreamAttribKHR glo_eglStreamAttribKHR
GLO_API_CALL PFNEGLSTREAMCONSUMERACQUIREATTRIBKHRPROC glo_eglStreamConsumerAcquireAttribKHR;
#define eglStreamConsumerAcquireAttribKHR glo_eglStreamConsumerAcquireAttribKHR
GLO_API_CALL PFNEGLSTREAMCONSUMERACQUIREKHRPROC glo_eglStreamConsumerAcquireKHR;
#define eglStreamConsumerAcquireKHR glo_eglStreamConsumerAcquireKHR
GLO_API_CALL PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALATTRIBSNVPROC glo_eglStreamConsumerGLTextureExternalAttribsNV;
#define eglStreamConsumerGLTextureExternalAttribsNV glo_eglStreamConsumerGLTextureExternalAttribsNV
GLO_API_CALL PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALKHRPROC glo_eglStreamConsumerGLTextureExternalKHR;
#define eglStreamConsumerGLTextureExternalKHR glo_eglStreamConsumerGLTextureExternalKHR
GLO_API_CALL PFNEGLSTREAMCONSUMEROUTPUTEXTPROC glo_eglStreamConsumerOutputEXT;
#define eglStreamConsumerOutputEXT glo_eglStreamConsumerOutputEXT
GLO_API_CALL PFNEGLSTREAMCONSUMERRELEASEATTRIBKHRPROC glo_eglStreamConsumerReleaseAttribKHR;
#define eglStreamConsumerReleaseAttribKHR glo_eglStreamConsumerReleaseAttribKHR
GLO_API_CALL PFNEGLSTREAMCONSUMERRELEASEKHRPROC glo_eglStreamConsumerReleaseKHR;
#define eglStreamConsumerReleaseKHR glo_eglStreamConsumerReleaseKHR
GLO_API_CALL PFNEGLSTREAMFLUSHNVPROC glo_eglStreamFlushNV;
#define eglStreamFlushNV glo_eglStreamFlushNV
GLO_API_CALL PFNEGLSTREAMIMAGECONSUMERCONNECTNVPROC glo_eglStreamImageConsumerConnectNV;
#define eglStreamImageConsumerConnectNV glo_eglStreamImageConsumerConnectNV
GLO_API_CALL PFNEGLSTREAMRELEASEIMAGENVPROC glo_eglStreamReleaseImageNV;
#define eglStreamReleaseImageNV glo_eglStreamReleaseImageNV
GLO_API_CALL PFNEGLSURFACEATTRIBPROC glo_eglSurfaceAttrib;
#define eglSurfaceAttrib glo_eglSurfaceAttrib
GLO_API_CALL PFNEGLSWAPBUFFERSPROC glo_eglSwapBuffers;
#define eglSwapBuffers glo_eglSwapBuffers
GLO_API_CALL PFNEGLSWAPBUFFERSREGION2NOKPROC glo_eglSwapBuffersRegion2NOK;
#define eglSwapBuffersRegion2NOK glo_eglSwapBuffersRegion2NOK
GLO_API_CALL PFNEGLSWAPBUFFERSREGIONNOKPROC glo_eglSwapBuffersRegionNOK;
#define eglSwapBuffersRegionNOK glo_eglSwapBuffersRegionNOK
GLO_API_CALL PFNEGLSWAPBUFFERSWITHDAMAGEEXTPROC glo_eglSwapBuffersWithDamageEXT;
#define eglSwapBuffersWithDamageEXT glo_eglSwapBuffersWithDamageEXT
GLO_API_CALL PFNEGLSWAPBUFFERSWITHDAMAGEKHRPROC glo_eglSwapBuffersWithDamageKHR;
#define eglSwapBuffersWithDamageKHR glo_eglSwapBuffersWithDamageKHR
GLO_API_CALL PFNEGLSWAPINTERVALPROC glo_eglSwapInterval;
#define eglSwapInterval glo_eglSwapInterval
GLO_API_CALL PFNEGLTERMINATEPROC glo_eglTerminate;
#define eglTerminate glo_eglTerminate
GLO_API_CALL PFNEGLUNBINDWAYLANDDISPLAYWLPROC glo_eglUnbindWaylandDisplayWL;
#define eglUnbindWaylandDisplayWL glo_eglUnbindWaylandDisplayWL
GLO_API_CALL PFNEGLUNLOCKSURFACEKHRPROC glo_eglUnlockSurfaceKHR;
#define eglUnlockSurfaceKHR glo_eglUnlockSurfaceKHR
GLO_API_CALL PFNEGLUNSIGNALSYNCEXTPROC glo_eglUnsignalSyncEXT;
#define eglUnsignalSyncEXT glo_eglUnsignalSyncEXT
GLO_API_CALL PFNEGLWAITCLIENTPROC glo_eglWaitClient;
#define eglWaitClient glo_eglWaitClient
GLO_API_CALL PFNEGLWAITGLPROC glo_eglWaitGL;
#define eglWaitGL glo_eglWaitGL
GLO_API_CALL PFNEGLWAITNATIVEPROC glo_eglWaitNative;
#define eglWaitNative glo_eglWaitNative
GLO_API_CALL PFNEGLWAITSYNCPROC glo_eglWaitSync;
#define eglWaitSync glo_eglWaitSync
GLO_API_CALL PFNEGLWAITSYNCKHRPROC glo_eglWaitSyncKHR;
#define eglWaitSyncKHR glo_eglWaitSyncKHR





GLO_API_CALL int gloLoadEGLUserPtr(EGLDisplay display, GLOuserptrloadfunc load, void *userptr);
GLO_API_CALL int gloLoadEGL(EGLDisplay display, GLOloadfunc load);

#ifdef GLO_EGL

GLO_API_CALL int gloLoaderLoadEGL(EGLDisplay display);

GLO_API_CALL void gloLoaderUnloadEGL(void);

#endif
#ifdef __cplusplus
}
#endif
#endif
