#ifndef GLO_WGL_H_
#define GLO_WGL_H_

#if !__has_include(<windows.h>)
  #error "windows.h wasn't found."
#else

#include <windows.h>
#include <glo/gl.h>

#define GLO_WGL
#define GLO_OPTION_WGL_LOADER

#ifdef __cplusplus
extern "C" {
#endif

#ifndef GLO_PLATFORM_H_
#define GLO_PLATFORM_H_

#ifndef GLO_PLATFORM_WIN32
  #if defined(_WIN32) || defined(__WIN32__) || defined(WIN32) || defined(__MINGW32__)
    #define GLO_PLATFORM_WIN32 1
  #else
    #define GLO_PLATFORM_WIN32 0
  #endif
#endif

#ifndef GLO_PLATFORM_APPLE
  #ifdef __APPLE__
    #define GLO_PLATFORM_APPLE 1
  #else
    #define GLO_PLATFORM_APPLE 0
  #endif
#endif

#ifndef GLO_PLATFORM_EMSCRIPTEN
  #ifdef __EMSCRIPTEN__
    #define GLO_PLATFORM_EMSCRIPTEN 1
  #else
    #define GLO_PLATFORM_EMSCRIPTEN 0
  #endif
#endif

#ifndef GLO_PLATFORM_UWP
  #if defined(_MSC_VER) && !defined(GLO_INTERNAL_HAVE_WINAPIFAMILY)
    #ifdef __has_include
      #if __has_include(<winapifamily.h>)
        #define GLO_INTERNAL_HAVE_WINAPIFAMILY 1
      #endif
    #elif _MSC_VER >= 1700 && !_USING_V110_SDK71_
      #define GLO_INTERNAL_HAVE_WINAPIFAMILY 1
    #endif
  #endif

  #ifdef GLO_INTERNAL_HAVE_WINAPIFAMILY
    #include <winapifamily.h>
    #if !WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
      #define GLO_PLATFORM_UWP 1
    #endif
  #endif

  #ifndef GLO_PLATFORM_UWP
    #define GLO_PLATFORM_UWP 0
  #endif
#endif

#ifdef __GNUC__
  #define GLO_GNUC_EXTENSION __extension__
#else
  #define GLO_GNUC_EXTENSION
#endif

#define GLO_UNUSED(x) (void)(x)

#ifndef GLO_API_CALL
  #if defined(GLO_API_CALL_EXPORT)
    #if GLO_PLATFORM_WIN32 || defined(__CYGWIN__)
      #if defined(GLO_API_CALL_EXPORT_BUILD)
        #if defined(__GNUC__)
          #define GLO_API_CALL __attribute__ ((dllexport)) extern
        #else
          #define GLO_API_CALL __declspec(dllexport) extern
        #endif
      #else
        #if defined(__GNUC__)
          #define GLO_API_CALL __attribute__ ((dllimport)) extern
        #else
          #define GLO_API_CALL __declspec(dllimport) extern
        #endif
      #endif
    #elif defined(__GNUC__) && defined(GLO_API_CALL_EXPORT_BUILD)
      #define GLO_API_CALL __attribute__ ((visibility ("default"))) extern
    #else
      #define GLO_API_CALL extern
    #endif
  #else
    #define GLO_API_CALL extern
  #endif
#endif

#ifdef APIENTRY
  #define GLO_API_PTR APIENTRY
#elif GLO_PLATFORM_WIN32
  #define GLO_API_PTR __stdcall
#else
  #define GLO_API_PTR
#endif

#ifndef GLAPI
#define GLAPI GLO_API_CALL
#endif

#ifndef GLAPIENTRY
#define GLAPIENTRY GLO_API_PTR
#endif

#define GLO_MAKE_VERSION(major, minor) (major * 10000 + minor)
#define GLO_VERSION_MAJOR(version) (version / 10000)
#define GLO_VERSION_MINOR(version) (version % 10000)

#define GLO_GENERATOR_VERSION "2.0.8"

typedef void (*GLOapiproc)(void);

typedef GLOapiproc (*GLOloadfunc)(const char *name);
typedef GLOapiproc (*GLOuserptrloadfunc)(void *userptr, const char *name);

typedef void (*GLOprecallback)(const char *name, GLOapiproc apiproc, int len_args, ...);
typedef void (*GLOpostcallback)(void *ret, const char *name, GLOapiproc apiproc, int len_args, ...);

#endif /* GLO_PLATFORM_H_ */

#define ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV 0x20D0
#define ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB 0x2054
#define ERROR_INVALID_PIXEL_TYPE_ARB 0x2043
#define ERROR_INVALID_PIXEL_TYPE_EXT 0x2043
#define ERROR_INVALID_PROFILE_ARB 0x2096
#define ERROR_INVALID_VERSION_ARB 0x2095
#define ERROR_MISSING_AFFINITY_MASK_NV 0x20D1
#define WGL_ACCELERATION_ARB 0x2003
#define WGL_ACCELERATION_EXT 0x2003
#define WGL_ACCESS_READ_ONLY_NV 0x00000000
#define WGL_ACCESS_READ_WRITE_NV 0x00000001
#define WGL_ACCESS_WRITE_DISCARD_NV 0x00000002
#define WGL_ACCUM_ALPHA_BITS_ARB 0x2021
#define WGL_ACCUM_ALPHA_BITS_EXT 0x2021
#define WGL_ACCUM_BITS_ARB 0x201D
#define WGL_ACCUM_BITS_EXT 0x201D
#define WGL_ACCUM_BLUE_BITS_ARB 0x2020
#define WGL_ACCUM_BLUE_BITS_EXT 0x2020
#define WGL_ACCUM_GREEN_BITS_ARB 0x201F
#define WGL_ACCUM_GREEN_BITS_EXT 0x201F
#define WGL_ACCUM_RED_BITS_ARB 0x201E
#define WGL_ACCUM_RED_BITS_EXT 0x201E
#define WGL_ALPHA_BITS_ARB 0x201B
#define WGL_ALPHA_BITS_EXT 0x201B
#define WGL_ALPHA_SHIFT_ARB 0x201C
#define WGL_ALPHA_SHIFT_EXT 0x201C
#define WGL_AUX0_ARB 0x2087
#define WGL_AUX1_ARB 0x2088
#define WGL_AUX2_ARB 0x2089
#define WGL_AUX3_ARB 0x208A
#define WGL_AUX4_ARB 0x208B
#define WGL_AUX5_ARB 0x208C
#define WGL_AUX6_ARB 0x208D
#define WGL_AUX7_ARB 0x208E
#define WGL_AUX8_ARB 0x208F
#define WGL_AUX9_ARB 0x2090
#define WGL_AUX_BUFFERS_ARB 0x2024
#define WGL_AUX_BUFFERS_EXT 0x2024
#define WGL_BACK_COLOR_BUFFER_BIT_ARB 0x00000002
#define WGL_BACK_LEFT_ARB 0x2085
#define WGL_BACK_RIGHT_ARB 0x2086
#define WGL_BIND_TO_TEXTURE_DEPTH_NV 0x20A3
#define WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV 0x20A4
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV 0x20B4
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV 0x20B3
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV 0x20B2
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV 0x20B1
#define WGL_BIND_TO_TEXTURE_RECTANGLE_RGBA_NV 0x20A1
#define WGL_BIND_TO_TEXTURE_RECTANGLE_RGB_NV 0x20A0
#define WGL_BIND_TO_TEXTURE_RGBA_ARB 0x2071
#define WGL_BIND_TO_TEXTURE_RGB_ARB 0x2070
#define WGL_BIND_TO_VIDEO_RGBA_NV 0x20C1
#define WGL_BIND_TO_VIDEO_RGB_AND_DEPTH_NV 0x20C2
#define WGL_BIND_TO_VIDEO_RGB_NV 0x20C0
#define WGL_BLUE_BITS_ARB 0x2019
#define WGL_BLUE_BITS_EXT 0x2019
#define WGL_BLUE_SHIFT_ARB 0x201A
#define WGL_BLUE_SHIFT_EXT 0x201A
#define WGL_COLORSPACE_EXT 0x309D
#define WGL_COLORSPACE_LINEAR_EXT 0x308A
#define WGL_COLORSPACE_SRGB_EXT 0x3089
#define WGL_COLOR_BITS_ARB 0x2014
#define WGL_COLOR_BITS_EXT 0x2014
#define WGL_COLOR_SAMPLES_NV 0x20B9
#define WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB 0x00000002
#define WGL_CONTEXT_CORE_PROFILE_BIT_ARB 0x00000001
#define WGL_CONTEXT_DEBUG_BIT_ARB 0x00000001
#define WGL_CONTEXT_ES2_PROFILE_BIT_EXT 0x00000004
#define WGL_CONTEXT_ES_PROFILE_BIT_EXT 0x00000004
#define WGL_CONTEXT_FLAGS_ARB 0x2094
#define WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB 0x00000002
#define WGL_CONTEXT_LAYER_PLANE_ARB 0x2093
#define WGL_CONTEXT_MAJOR_VERSION_ARB 0x2091
#define WGL_CONTEXT_MINOR_VERSION_ARB 0x2092
#define WGL_CONTEXT_MULTIGPU_ATTRIB_AFR_NV 0x20AC
#define WGL_CONTEXT_MULTIGPU_ATTRIB_MULTICAST_NV 0x20AD
#define WGL_CONTEXT_MULTIGPU_ATTRIB_MULTI_DISPLAY_MULTICAST_NV 0x20AE
#define WGL_CONTEXT_MULTIGPU_ATTRIB_NV 0x20AA
#define WGL_CONTEXT_MULTIGPU_ATTRIB_SINGLE_NV 0x20AB
#define WGL_CONTEXT_OPENGL_NO_ERROR_ARB 0x31B3
#define WGL_CONTEXT_PROFILE_MASK_ARB 0x9126
#define WGL_CONTEXT_RELEASE_BEHAVIOR_ARB 0x2097
#define WGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB 0x2098
#define WGL_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB 0
#define WGL_CONTEXT_RESET_ISOLATION_BIT_ARB 0x00000008
#define WGL_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB 0x8256
#define WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB 0x00000004
#define WGL_COVERAGE_SAMPLES_NV 0x2042
#define WGL_CUBE_MAP_FACE_ARB 0x207C
#define WGL_DEPTH_BITS_ARB 0x2022
#define WGL_DEPTH_BITS_EXT 0x2022
#define WGL_DEPTH_BUFFER_BIT_ARB 0x00000004
#define WGL_DEPTH_COMPONENT_NV 0x20A7
#define WGL_DEPTH_FLOAT_EXT 0x2040
#define WGL_DEPTH_TEXTURE_FORMAT_NV 0x20A5
#define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D 0x2050
#define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D 0x2051
#define WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D 0x2052
#define WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D 0x2053
#define WGL_DOUBLE_BUFFER_ARB 0x2011
#define WGL_DOUBLE_BUFFER_EXT 0x2011
#define WGL_DRAW_TO_BITMAP_ARB 0x2002
#define WGL_DRAW_TO_BITMAP_EXT 0x2002
#define WGL_DRAW_TO_PBUFFER_ARB 0x202D
#define WGL_DRAW_TO_PBUFFER_EXT 0x202D
#define WGL_DRAW_TO_WINDOW_ARB 0x2001
#define WGL_DRAW_TO_WINDOW_EXT 0x2001
#define WGL_FLOAT_COMPONENTS_NV 0x20B0
#define WGL_FONT_LINES 0
#define WGL_FONT_POLYGONS 1
#define WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB 0x20A9
#define WGL_FRAMEBUFFER_SRGB_CAPABLE_EXT 0x20A9
#define WGL_FRONT_COLOR_BUFFER_BIT_ARB 0x00000001
#define WGL_FRONT_LEFT_ARB 0x2083
#define WGL_FRONT_RIGHT_ARB 0x2084
#define WGL_FULL_ACCELERATION_ARB 0x2027
#define WGL_FULL_ACCELERATION_EXT 0x2027
#define WGL_GAMMA_EXCLUDE_DESKTOP_I3D 0x204F
#define WGL_GAMMA_TABLE_SIZE_I3D 0x204E
#define WGL_GENERIC_ACCELERATION_ARB 0x2026
#define WGL_GENERIC_ACCELERATION_EXT 0x2026
#define WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D 0x2049
#define WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D 0x2048
#define WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D 0x204C
#define WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D 0x204A
#define WGL_GENLOCK_SOURCE_EDGE_RISING_I3D 0x204B
#define WGL_GENLOCK_SOURCE_EXTERNAL_FIELD_I3D 0x2046
#define WGL_GENLOCK_SOURCE_EXTERNAL_SYNC_I3D 0x2045
#define WGL_GENLOCK_SOURCE_EXTERNAL_TTL_I3D 0x2047
#define WGL_GENLOCK_SOURCE_MULTIVIEW_I3D 0x2044
#define WGL_GPU_CLOCK_AMD 0x21A4
#define WGL_GPU_FASTEST_TARGET_GPUS_AMD 0x21A2
#define WGL_GPU_NUM_PIPES_AMD 0x21A5
#define WGL_GPU_NUM_RB_AMD 0x21A7
#define WGL_GPU_NUM_SIMD_AMD 0x21A6
#define WGL_GPU_NUM_SPI_AMD 0x21A8
#define WGL_GPU_OPENGL_VERSION_STRING_AMD 0x1F02
#define WGL_GPU_RAM_AMD 0x21A3
#define WGL_GPU_RENDERER_STRING_AMD 0x1F01
#define WGL_GPU_VENDOR_AMD 0x1F00
#define WGL_GREEN_BITS_ARB 0x2017
#define WGL_GREEN_BITS_EXT 0x2017
#define WGL_GREEN_SHIFT_ARB 0x2018
#define WGL_GREEN_SHIFT_EXT 0x2018
#define WGL_IMAGE_BUFFER_LOCK_I3D 0x00000002
#define WGL_IMAGE_BUFFER_MIN_ACCESS_I3D 0x00000001
#define WGL_LOSE_CONTEXT_ON_RESET_ARB 0x8252
#define WGL_MAX_PBUFFER_HEIGHT_ARB 0x2030
#define WGL_MAX_PBUFFER_HEIGHT_EXT 0x2030
#define WGL_MAX_PBUFFER_PIXELS_ARB 0x202E
#define WGL_MAX_PBUFFER_PIXELS_EXT 0x202E
#define WGL_MAX_PBUFFER_WIDTH_ARB 0x202F
#define WGL_MAX_PBUFFER_WIDTH_EXT 0x202F
#define WGL_MIPMAP_LEVEL_ARB 0x207B
#define WGL_MIPMAP_TEXTURE_ARB 0x2074
#define WGL_NEED_PALETTE_ARB 0x2004
#define WGL_NEED_PALETTE_EXT 0x2004
#define WGL_NEED_SYSTEM_PALETTE_ARB 0x2005
#define WGL_NEED_SYSTEM_PALETTE_EXT 0x2005
#define WGL_NO_ACCELERATION_ARB 0x2025
#define WGL_NO_ACCELERATION_EXT 0x2025
#define WGL_NO_RESET_NOTIFICATION_ARB 0x8261
#define WGL_NO_TEXTURE_ARB 0x2077
#define WGL_NUMBER_OVERLAYS_ARB 0x2008
#define WGL_NUMBER_OVERLAYS_EXT 0x2008
#define WGL_NUMBER_PIXEL_FORMATS_ARB 0x2000
#define WGL_NUMBER_PIXEL_FORMATS_EXT 0x2000
#define WGL_NUMBER_UNDERLAYS_ARB 0x2009
#define WGL_NUMBER_UNDERLAYS_EXT 0x2009
#define WGL_NUM_VIDEO_CAPTURE_SLOTS_NV 0x20CF
#define WGL_NUM_VIDEO_SLOTS_NV 0x20F0
#define WGL_OPTIMAL_PBUFFER_HEIGHT_EXT 0x2032
#define WGL_OPTIMAL_PBUFFER_WIDTH_EXT 0x2031
#define WGL_PBUFFER_HEIGHT_ARB 0x2035
#define WGL_PBUFFER_HEIGHT_EXT 0x2035
#define WGL_PBUFFER_LARGEST_ARB 0x2033
#define WGL_PBUFFER_LARGEST_EXT 0x2033
#define WGL_PBUFFER_LOST_ARB 0x2036
#define WGL_PBUFFER_WIDTH_ARB 0x2034
#define WGL_PBUFFER_WIDTH_EXT 0x2034
#define WGL_PIXEL_TYPE_ARB 0x2013
#define WGL_PIXEL_TYPE_EXT 0x2013
#define WGL_RED_BITS_ARB 0x2015
#define WGL_RED_BITS_EXT 0x2015
#define WGL_RED_SHIFT_ARB 0x2016
#define WGL_RED_SHIFT_EXT 0x2016
#define WGL_SAMPLES_3DFX 0x2061
#define WGL_SAMPLES_ARB 0x2042
#define WGL_SAMPLES_EXT 0x2042
#define WGL_SAMPLE_BUFFERS_3DFX 0x2060
#define WGL_SAMPLE_BUFFERS_ARB 0x2041
#define WGL_SAMPLE_BUFFERS_EXT 0x2041
#define WGL_SHARE_ACCUM_ARB 0x200E
#define WGL_SHARE_ACCUM_EXT 0x200E
#define WGL_SHARE_DEPTH_ARB 0x200C
#define WGL_SHARE_DEPTH_EXT 0x200C
#define WGL_SHARE_STENCIL_ARB 0x200D
#define WGL_SHARE_STENCIL_EXT 0x200D
#define WGL_STENCIL_BITS_ARB 0x2023
#define WGL_STENCIL_BITS_EXT 0x2023
#define WGL_STENCIL_BUFFER_BIT_ARB 0x00000008
#define WGL_STEREO_ARB 0x2012
#define WGL_STEREO_EMITTER_DISABLE_3DL 0x2056
#define WGL_STEREO_EMITTER_ENABLE_3DL 0x2055
#define WGL_STEREO_EXT 0x2012
#define WGL_STEREO_POLARITY_INVERT_3DL 0x2058
#define WGL_STEREO_POLARITY_NORMAL_3DL 0x2057
#define WGL_SUPPORT_GDI_ARB 0x200F
#define WGL_SUPPORT_GDI_EXT 0x200F
#define WGL_SUPPORT_OPENGL_ARB 0x2010
#define WGL_SUPPORT_OPENGL_EXT 0x2010
#define WGL_SWAP_COPY_ARB 0x2029
#define WGL_SWAP_COPY_EXT 0x2029
#define WGL_SWAP_EXCHANGE_ARB 0x2028
#define WGL_SWAP_EXCHANGE_EXT 0x2028
#define WGL_SWAP_LAYER_BUFFERS_ARB 0x2006
#define WGL_SWAP_LAYER_BUFFERS_EXT 0x2006
#define WGL_SWAP_MAIN_PLANE 0x00000001
#define WGL_SWAP_METHOD_ARB 0x2007
#define WGL_SWAP_METHOD_EXT 0x2007
#define WGL_SWAP_OVERLAY1 0x00000002
#define WGL_SWAP_OVERLAY10 0x00000400
#define WGL_SWAP_OVERLAY11 0x00000800
#define WGL_SWAP_OVERLAY12 0x00001000
#define WGL_SWAP_OVERLAY13 0x00002000
#define WGL_SWAP_OVERLAY14 0x00004000
#define WGL_SWAP_OVERLAY15 0x00008000
#define WGL_SWAP_OVERLAY2 0x00000004
#define WGL_SWAP_OVERLAY3 0x00000008
#define WGL_SWAP_OVERLAY4 0x00000010
#define WGL_SWAP_OVERLAY5 0x00000020
#define WGL_SWAP_OVERLAY6 0x00000040
#define WGL_SWAP_OVERLAY7 0x00000080
#define WGL_SWAP_OVERLAY8 0x00000100
#define WGL_SWAP_OVERLAY9 0x00000200
#define WGL_SWAP_UNDEFINED_ARB 0x202A
#define WGL_SWAP_UNDEFINED_EXT 0x202A
#define WGL_SWAP_UNDERLAY1 0x00010000
#define WGL_SWAP_UNDERLAY10 0x02000000
#define WGL_SWAP_UNDERLAY11 0x04000000
#define WGL_SWAP_UNDERLAY12 0x08000000
#define WGL_SWAP_UNDERLAY13 0x10000000
#define WGL_SWAP_UNDERLAY14 0x20000000
#define WGL_SWAP_UNDERLAY15 0x40000000
#define WGL_SWAP_UNDERLAY2 0x00020000
#define WGL_SWAP_UNDERLAY3 0x00040000
#define WGL_SWAP_UNDERLAY4 0x00080000
#define WGL_SWAP_UNDERLAY5 0x00100000
#define WGL_SWAP_UNDERLAY6 0x00200000
#define WGL_SWAP_UNDERLAY7 0x00400000
#define WGL_SWAP_UNDERLAY8 0x00800000
#define WGL_SWAP_UNDERLAY9 0x01000000
#define WGL_TEXTURE_1D_ARB 0x2079
#define WGL_TEXTURE_2D_ARB 0x207A
#define WGL_TEXTURE_CUBE_MAP_ARB 0x2078
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB 0x207E
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB 0x2080
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB 0x2082
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB 0x207D
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB 0x207F
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB 0x2081
#define WGL_TEXTURE_DEPTH_COMPONENT_NV 0x20A6
#define WGL_TEXTURE_FLOAT_RGBA_NV 0x20B8
#define WGL_TEXTURE_FLOAT_RGB_NV 0x20B7
#define WGL_TEXTURE_FLOAT_RG_NV 0x20B6
#define WGL_TEXTURE_FLOAT_R_NV 0x20B5
#define WGL_TEXTURE_FORMAT_ARB 0x2072
#define WGL_TEXTURE_RECTANGLE_ATI 0x21A5
#define WGL_TEXTURE_RECTANGLE_NV 0x20A2
#define WGL_TEXTURE_RGBA_ARB 0x2076
#define WGL_TEXTURE_RGB_ARB 0x2075
#define WGL_TEXTURE_TARGET_ARB 0x2073
#define WGL_TRANSPARENT_ALPHA_VALUE_ARB 0x203A
#define WGL_TRANSPARENT_ARB 0x200A
#define WGL_TRANSPARENT_BLUE_VALUE_ARB 0x2039
#define WGL_TRANSPARENT_EXT 0x200A
#define WGL_TRANSPARENT_GREEN_VALUE_ARB 0x2038
#define WGL_TRANSPARENT_INDEX_VALUE_ARB 0x203B
#define WGL_TRANSPARENT_RED_VALUE_ARB 0x2037
#define WGL_TRANSPARENT_VALUE_EXT 0x200B
#define WGL_TYPE_COLORINDEX_ARB 0x202C
#define WGL_TYPE_COLORINDEX_EXT 0x202C
#define WGL_TYPE_RGBA_ARB 0x202B
#define WGL_TYPE_RGBA_EXT 0x202B
#define WGL_TYPE_RGBA_FLOAT_ARB 0x21A0
#define WGL_TYPE_RGBA_FLOAT_ATI 0x21A0
#define WGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT 0x20A8
#define WGL_UNIQUE_ID_NV 0x20CE
#define WGL_VIDEO_OUT_ALPHA_NV 0x20C4
#define WGL_VIDEO_OUT_COLOR_AND_ALPHA_NV 0x20C6
#define WGL_VIDEO_OUT_COLOR_AND_DEPTH_NV 0x20C7
#define WGL_VIDEO_OUT_COLOR_NV 0x20C3
#define WGL_VIDEO_OUT_DEPTH_NV 0x20C5
#define WGL_VIDEO_OUT_FIELD_1 0x20C9
#define WGL_VIDEO_OUT_FIELD_2 0x20CA
#define WGL_VIDEO_OUT_FRAME 0x20C8
#define WGL_VIDEO_OUT_STACKED_FIELDS_1_2 0x20CB
#define WGL_VIDEO_OUT_STACKED_FIELDS_2_1 0x20CC
































struct _GPU_DEVICE {
    DWORD  cb;
    CHAR   DeviceName[32];
    CHAR   DeviceString[128];
    DWORD  Flags;
    RECT   rcVirtualScreen;
};
DECLARE_HANDLE(HPBUFFERARB);
DECLARE_HANDLE(HPBUFFEREXT);
DECLARE_HANDLE(HVIDEOOUTPUTDEVICENV);
DECLARE_HANDLE(HPVIDEODEV);
DECLARE_HANDLE(HPGPUNV);
DECLARE_HANDLE(HGPUNV);
DECLARE_HANDLE(HVIDEOINPUTDEVICENV);
typedef struct _GPU_DEVICE GPU_DEVICE;
typedef struct _GPU_DEVICE *PGPU_DEVICE;


#define WGL_VERSION_1_0 1
GLO_API_CALL int GLO_WGL_VERSION_1_0;
#define WGL_3DFX_multisample 1
GLO_API_CALL int GLO_WGL_3DFX_multisample;
#define WGL_3DL_stereo_control 1
GLO_API_CALL int GLO_WGL_3DL_stereo_control;
#define WGL_AMD_gpu_association 1
GLO_API_CALL int GLO_WGL_AMD_gpu_association;
#define WGL_ARB_buffer_region 1
GLO_API_CALL int GLO_WGL_ARB_buffer_region;
#define WGL_ARB_context_flush_control 1
GLO_API_CALL int GLO_WGL_ARB_context_flush_control;
#define WGL_ARB_create_context 1
GLO_API_CALL int GLO_WGL_ARB_create_context;
#define WGL_ARB_create_context_no_error 1
GLO_API_CALL int GLO_WGL_ARB_create_context_no_error;
#define WGL_ARB_create_context_profile 1
GLO_API_CALL int GLO_WGL_ARB_create_context_profile;
#define WGL_ARB_create_context_robustness 1
GLO_API_CALL int GLO_WGL_ARB_create_context_robustness;
#define WGL_ARB_extensions_string 1
GLO_API_CALL int GLO_WGL_ARB_extensions_string;
#define WGL_ARB_framebuffer_sRGB 1
GLO_API_CALL int GLO_WGL_ARB_framebuffer_sRGB;
#define WGL_ARB_make_current_read 1
GLO_API_CALL int GLO_WGL_ARB_make_current_read;
#define WGL_ARB_multisample 1
GLO_API_CALL int GLO_WGL_ARB_multisample;
#define WGL_ARB_pbuffer 1
GLO_API_CALL int GLO_WGL_ARB_pbuffer;
#define WGL_ARB_pixel_format 1
GLO_API_CALL int GLO_WGL_ARB_pixel_format;
#define WGL_ARB_pixel_format_float 1
GLO_API_CALL int GLO_WGL_ARB_pixel_format_float;
#define WGL_ARB_render_texture 1
GLO_API_CALL int GLO_WGL_ARB_render_texture;
#define WGL_ARB_robustness_application_isolation 1
GLO_API_CALL int GLO_WGL_ARB_robustness_application_isolation;
#define WGL_ARB_robustness_share_group_isolation 1
GLO_API_CALL int GLO_WGL_ARB_robustness_share_group_isolation;
#define WGL_ATI_pixel_format_float 1
GLO_API_CALL int GLO_WGL_ATI_pixel_format_float;
#define WGL_ATI_render_texture_rectangle 1
GLO_API_CALL int GLO_WGL_ATI_render_texture_rectangle;
#define WGL_EXT_colorspace 1
GLO_API_CALL int GLO_WGL_EXT_colorspace;
#define WGL_EXT_create_context_es2_profile 1
GLO_API_CALL int GLO_WGL_EXT_create_context_es2_profile;
#define WGL_EXT_create_context_es_profile 1
GLO_API_CALL int GLO_WGL_EXT_create_context_es_profile;
#define WGL_EXT_depth_float 1
GLO_API_CALL int GLO_WGL_EXT_depth_float;
#define WGL_EXT_display_color_table 1
GLO_API_CALL int GLO_WGL_EXT_display_color_table;
#define WGL_EXT_extensions_string 1
GLO_API_CALL int GLO_WGL_EXT_extensions_string;
#define WGL_EXT_framebuffer_sRGB 1
GLO_API_CALL int GLO_WGL_EXT_framebuffer_sRGB;
#define WGL_EXT_make_current_read 1
GLO_API_CALL int GLO_WGL_EXT_make_current_read;
#define WGL_EXT_multisample 1
GLO_API_CALL int GLO_WGL_EXT_multisample;
#define WGL_EXT_pbuffer 1
GLO_API_CALL int GLO_WGL_EXT_pbuffer;
#define WGL_EXT_pixel_format 1
GLO_API_CALL int GLO_WGL_EXT_pixel_format;
#define WGL_EXT_pixel_format_packed_float 1
GLO_API_CALL int GLO_WGL_EXT_pixel_format_packed_float;
#define WGL_EXT_swap_control 1
GLO_API_CALL int GLO_WGL_EXT_swap_control;
#define WGL_EXT_swap_control_tear 1
GLO_API_CALL int GLO_WGL_EXT_swap_control_tear;
#define WGL_I3D_digital_video_control 1
GLO_API_CALL int GLO_WGL_I3D_digital_video_control;
#define WGL_I3D_gamma 1
GLO_API_CALL int GLO_WGL_I3D_gamma;
#define WGL_I3D_genlock 1
GLO_API_CALL int GLO_WGL_I3D_genlock;
#define WGL_I3D_image_buffer 1
GLO_API_CALL int GLO_WGL_I3D_image_buffer;
#define WGL_I3D_swap_frame_lock 1
GLO_API_CALL int GLO_WGL_I3D_swap_frame_lock;
#define WGL_I3D_swap_frame_usage 1
GLO_API_CALL int GLO_WGL_I3D_swap_frame_usage;
#define WGL_NV_DX_interop 1
GLO_API_CALL int GLO_WGL_NV_DX_interop;
#define WGL_NV_DX_interop2 1
GLO_API_CALL int GLO_WGL_NV_DX_interop2;
#define WGL_NV_copy_image 1
GLO_API_CALL int GLO_WGL_NV_copy_image;
#define WGL_NV_delay_before_swap 1
GLO_API_CALL int GLO_WGL_NV_delay_before_swap;
#define WGL_NV_float_buffer 1
GLO_API_CALL int GLO_WGL_NV_float_buffer;
#define WGL_NV_gpu_affinity 1
GLO_API_CALL int GLO_WGL_NV_gpu_affinity;
#define WGL_NV_multigpu_context 1
GLO_API_CALL int GLO_WGL_NV_multigpu_context;
#define WGL_NV_multisample_coverage 1
GLO_API_CALL int GLO_WGL_NV_multisample_coverage;
#define WGL_NV_present_video 1
GLO_API_CALL int GLO_WGL_NV_present_video;
#define WGL_NV_render_depth_texture 1
GLO_API_CALL int GLO_WGL_NV_render_depth_texture;
#define WGL_NV_render_texture_rectangle 1
GLO_API_CALL int GLO_WGL_NV_render_texture_rectangle;
#define WGL_NV_swap_group 1
GLO_API_CALL int GLO_WGL_NV_swap_group;
#define WGL_NV_vertex_array_range 1
GLO_API_CALL int GLO_WGL_NV_vertex_array_range;
#define WGL_NV_video_capture 1
GLO_API_CALL int GLO_WGL_NV_video_capture;
#define WGL_NV_video_output 1
GLO_API_CALL int GLO_WGL_NV_video_output;
#define WGL_OML_sync_control 1
GLO_API_CALL int GLO_WGL_OML_sync_control;


typedef int (GLO_API_PTR *PFNCHOOSEPIXELFORMATPROC)(HDC hDc, const PIXELFORMATDESCRIPTOR * pPfd);
typedef int (GLO_API_PTR *PFNDESCRIBEPIXELFORMATPROC)(HDC hdc, int ipfd, UINT cjpfd, PIXELFORMATDESCRIPTOR * ppfd);
typedef UINT (GLO_API_PTR *PFNGETENHMETAFILEPIXELFORMATPROC)(HENHMETAFILE hemf, UINT cbBuffer, PIXELFORMATDESCRIPTOR * ppfd);
typedef int (GLO_API_PTR *PFNGETPIXELFORMATPROC)(HDC hdc);
typedef BOOL (GLO_API_PTR *PFNSETPIXELFORMATPROC)(HDC hdc, int ipfd, const PIXELFORMATDESCRIPTOR * ppfd);
typedef BOOL (GLO_API_PTR *PFNSWAPBUFFERSPROC)(HDC hdc);
typedef void * (GLO_API_PTR *PFNWGLALLOCATEMEMORYNVPROC)(GLsizei size, GLfloat readfreq, GLfloat writefreq, GLfloat priority);
typedef BOOL (GLO_API_PTR *PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC)(HDC hDC, const HANDLE * pEvent, const LPVOID * pAddress, const DWORD * pSize, UINT count);
typedef BOOL (GLO_API_PTR *PFNWGLBEGINFRAMETRACKINGI3DPROC)(void);
typedef GLboolean (GLO_API_PTR *PFNWGLBINDDISPLAYCOLORTABLEEXTPROC)(GLushort id);
typedef BOOL (GLO_API_PTR *PFNWGLBINDSWAPBARRIERNVPROC)(GLuint group, GLuint barrier);
typedef BOOL (GLO_API_PTR *PFNWGLBINDTEXIMAGEARBPROC)(HPBUFFERARB hPbuffer, int iBuffer);
typedef BOOL (GLO_API_PTR *PFNWGLBINDVIDEOCAPTUREDEVICENVPROC)(UINT uVideoSlot, HVIDEOINPUTDEVICENV hDevice);
typedef BOOL (GLO_API_PTR *PFNWGLBINDVIDEODEVICENVPROC)(HDC hDc, unsigned int uVideoSlot, HVIDEOOUTPUTDEVICENV hVideoDevice, const int * piAttribList);
typedef BOOL (GLO_API_PTR *PFNWGLBINDVIDEOIMAGENVPROC)(HPVIDEODEV hVideoDevice, HPBUFFERARB hPbuffer, int iVideoBuffer);
typedef VOID (GLO_API_PTR *PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC)(HGLRC dstCtx, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
typedef BOOL (GLO_API_PTR *PFNWGLCHOOSEPIXELFORMATARBPROC)(HDC hdc, const int * piAttribIList, const FLOAT * pfAttribFList, UINT nMaxFormats, int * piFormats, UINT * nNumFormats);
typedef BOOL (GLO_API_PTR *PFNWGLCHOOSEPIXELFORMATEXTPROC)(HDC hdc, const int * piAttribIList, const FLOAT * pfAttribFList, UINT nMaxFormats, int * piFormats, UINT * nNumFormats);
typedef BOOL (GLO_API_PTR *PFNWGLCOPYCONTEXTPROC)(HGLRC hglrcSrc, HGLRC hglrcDst, UINT mask);
typedef BOOL (GLO_API_PTR *PFNWGLCOPYIMAGESUBDATANVPROC)(HGLRC hSrcRC, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, HGLRC hDstRC, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei width, GLsizei height, GLsizei depth);
typedef HDC (GLO_API_PTR *PFNWGLCREATEAFFINITYDCNVPROC)(const HGPUNV * phGpuList);
typedef HGLRC (GLO_API_PTR *PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC)(UINT id);
typedef HGLRC (GLO_API_PTR *PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC)(UINT id, HGLRC hShareContext, const int * attribList);
typedef HANDLE (GLO_API_PTR *PFNWGLCREATEBUFFERREGIONARBPROC)(HDC hDC, int iLayerPlane, UINT uType);
typedef HGLRC (GLO_API_PTR *PFNWGLCREATECONTEXTPROC)(HDC hDc);
typedef HGLRC (GLO_API_PTR *PFNWGLCREATECONTEXTATTRIBSARBPROC)(HDC hDC, HGLRC hShareContext, const int * attribList);
typedef GLboolean (GLO_API_PTR *PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC)(GLushort id);
typedef LPVOID (GLO_API_PTR *PFNWGLCREATEIMAGEBUFFERI3DPROC)(HDC hDC, DWORD dwSize, UINT uFlags);
typedef HGLRC (GLO_API_PTR *PFNWGLCREATELAYERCONTEXTPROC)(HDC hDc, int level);
typedef HPBUFFERARB (GLO_API_PTR *PFNWGLCREATEPBUFFERARBPROC)(HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int * piAttribList);
typedef HPBUFFEREXT (GLO_API_PTR *PFNWGLCREATEPBUFFEREXTPROC)(HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int * piAttribList);
typedef BOOL (GLO_API_PTR *PFNWGLDXCLOSEDEVICENVPROC)(HANDLE hDevice);
typedef BOOL (GLO_API_PTR *PFNWGLDXLOCKOBJECTSNVPROC)(HANDLE hDevice, GLint count, HANDLE * hObjects);
typedef BOOL (GLO_API_PTR *PFNWGLDXOBJECTACCESSNVPROC)(HANDLE hObject, GLenum access);
typedef HANDLE (GLO_API_PTR *PFNWGLDXOPENDEVICENVPROC)(void * dxDevice);
typedef HANDLE (GLO_API_PTR *PFNWGLDXREGISTEROBJECTNVPROC)(HANDLE hDevice, void * dxObject, GLuint name, GLenum type, GLenum access);
typedef BOOL (GLO_API_PTR *PFNWGLDXSETRESOURCESHAREHANDLENVPROC)(void * dxObject, HANDLE shareHandle);
typedef BOOL (GLO_API_PTR *PFNWGLDXUNLOCKOBJECTSNVPROC)(HANDLE hDevice, GLint count, HANDLE * hObjects);
typedef BOOL (GLO_API_PTR *PFNWGLDXUNREGISTEROBJECTNVPROC)(HANDLE hDevice, HANDLE hObject);
typedef BOOL (GLO_API_PTR *PFNWGLDELAYBEFORESWAPNVPROC)(HDC hDC, GLfloat seconds);
typedef BOOL (GLO_API_PTR *PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC)(HGLRC hglrc);
typedef VOID (GLO_API_PTR *PFNWGLDELETEBUFFERREGIONARBPROC)(HANDLE hRegion);
typedef BOOL (GLO_API_PTR *PFNWGLDELETECONTEXTPROC)(HGLRC oldContext);
typedef BOOL (GLO_API_PTR *PFNWGLDELETEDCNVPROC)(HDC hdc);
typedef BOOL (GLO_API_PTR *PFNWGLDESCRIBELAYERPLANEPROC)(HDC hDc, int pixelFormat, int layerPlane, UINT nBytes, LAYERPLANEDESCRIPTOR * plpd);
typedef VOID (GLO_API_PTR *PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC)(GLushort id);
typedef BOOL (GLO_API_PTR *PFNWGLDESTROYIMAGEBUFFERI3DPROC)(HDC hDC, LPVOID pAddress);
typedef BOOL (GLO_API_PTR *PFNWGLDESTROYPBUFFERARBPROC)(HPBUFFERARB hPbuffer);
typedef BOOL (GLO_API_PTR *PFNWGLDESTROYPBUFFEREXTPROC)(HPBUFFEREXT hPbuffer);
typedef BOOL (GLO_API_PTR *PFNWGLDISABLEFRAMELOCKI3DPROC)(void);
typedef BOOL (GLO_API_PTR *PFNWGLDISABLEGENLOCKI3DPROC)(HDC hDC);
typedef BOOL (GLO_API_PTR *PFNWGLENABLEFRAMELOCKI3DPROC)(void);
typedef BOOL (GLO_API_PTR *PFNWGLENABLEGENLOCKI3DPROC)(HDC hDC);
typedef BOOL (GLO_API_PTR *PFNWGLENDFRAMETRACKINGI3DPROC)(void);
typedef BOOL (GLO_API_PTR *PFNWGLENUMGPUDEVICESNVPROC)(HGPUNV hGpu, UINT iDeviceIndex, PGPU_DEVICE lpGpuDevice);
typedef BOOL (GLO_API_PTR *PFNWGLENUMGPUSFROMAFFINITYDCNVPROC)(HDC hAffinityDC, UINT iGpuIndex, HGPUNV * hGpu);
typedef BOOL (GLO_API_PTR *PFNWGLENUMGPUSNVPROC)(UINT iGpuIndex, HGPUNV * phGpu);
typedef UINT (GLO_API_PTR *PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC)(HDC hDc, HVIDEOINPUTDEVICENV * phDeviceList);
typedef int (GLO_API_PTR *PFNWGLENUMERATEVIDEODEVICESNVPROC)(HDC hDc, HVIDEOOUTPUTDEVICENV * phDeviceList);
typedef void (GLO_API_PTR *PFNWGLFREEMEMORYNVPROC)(void * pointer);
typedef BOOL (GLO_API_PTR *PFNWGLGENLOCKSAMPLERATEI3DPROC)(HDC hDC, UINT uRate);
typedef BOOL (GLO_API_PTR *PFNWGLGENLOCKSOURCEDELAYI3DPROC)(HDC hDC, UINT uDelay);
typedef BOOL (GLO_API_PTR *PFNWGLGENLOCKSOURCEEDGEI3DPROC)(HDC hDC, UINT uEdge);
typedef BOOL (GLO_API_PTR *PFNWGLGENLOCKSOURCEI3DPROC)(HDC hDC, UINT uSource);
typedef UINT (GLO_API_PTR *PFNWGLGETCONTEXTGPUIDAMDPROC)(HGLRC hglrc);
typedef HGLRC (GLO_API_PTR *PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC)(void);
typedef HGLRC (GLO_API_PTR *PFNWGLGETCURRENTCONTEXTPROC)(void);
typedef HDC (GLO_API_PTR *PFNWGLGETCURRENTDCPROC)(void);
typedef HDC (GLO_API_PTR *PFNWGLGETCURRENTREADDCARBPROC)(void);
typedef HDC (GLO_API_PTR *PFNWGLGETCURRENTREADDCEXTPROC)(void);
typedef BOOL (GLO_API_PTR *PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC)(HDC hDC, int iAttribute, int * piValue);
typedef const char * (GLO_API_PTR *PFNWGLGETEXTENSIONSSTRINGARBPROC)(HDC hdc);
typedef const char * (GLO_API_PTR *PFNWGLGETEXTENSIONSSTRINGEXTPROC)(void);
typedef BOOL (GLO_API_PTR *PFNWGLGETFRAMEUSAGEI3DPROC)(float * pUsage);
typedef UINT (GLO_API_PTR *PFNWGLGETGPUIDSAMDPROC)(UINT maxCount, UINT * ids);
typedef INT (GLO_API_PTR *PFNWGLGETGPUINFOAMDPROC)(UINT id, INT property, GLenum dataType, UINT size, void * data);
typedef BOOL (GLO_API_PTR *PFNWGLGETGAMMATABLEI3DPROC)(HDC hDC, int iEntries, USHORT * puRed, USHORT * puGreen, USHORT * puBlue);
typedef BOOL (GLO_API_PTR *PFNWGLGETGAMMATABLEPARAMETERSI3DPROC)(HDC hDC, int iAttribute, int * piValue);
typedef BOOL (GLO_API_PTR *PFNWGLGETGENLOCKSAMPLERATEI3DPROC)(HDC hDC, UINT * uRate);
typedef BOOL (GLO_API_PTR *PFNWGLGETGENLOCKSOURCEDELAYI3DPROC)(HDC hDC, UINT * uDelay);
typedef BOOL (GLO_API_PTR *PFNWGLGETGENLOCKSOURCEEDGEI3DPROC)(HDC hDC, UINT * uEdge);
typedef BOOL (GLO_API_PTR *PFNWGLGETGENLOCKSOURCEI3DPROC)(HDC hDC, UINT * uSource);
typedef int (GLO_API_PTR *PFNWGLGETLAYERPALETTEENTRIESPROC)(HDC hdc, int iLayerPlane, int iStart, int cEntries, COLORREF * pcr);
typedef BOOL (GLO_API_PTR *PFNWGLGETMSCRATEOMLPROC)(HDC hdc, INT32 * numerator, INT32 * denominator);
typedef HDC (GLO_API_PTR *PFNWGLGETPBUFFERDCARBPROC)(HPBUFFERARB hPbuffer);
typedef HDC (GLO_API_PTR *PFNWGLGETPBUFFERDCEXTPROC)(HPBUFFEREXT hPbuffer);
typedef BOOL (GLO_API_PTR *PFNWGLGETPIXELFORMATATTRIBFVARBPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int * piAttributes, FLOAT * pfValues);
typedef BOOL (GLO_API_PTR *PFNWGLGETPIXELFORMATATTRIBFVEXTPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int * piAttributes, FLOAT * pfValues);
typedef BOOL (GLO_API_PTR *PFNWGLGETPIXELFORMATATTRIBIVARBPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int * piAttributes, int * piValues);
typedef BOOL (GLO_API_PTR *PFNWGLGETPIXELFORMATATTRIBIVEXTPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int * piAttributes, int * piValues);
typedef PROC (GLO_API_PTR *PFNWGLGETPROCADDRESSPROC)(LPCSTR lpszProc);
typedef int (GLO_API_PTR *PFNWGLGETSWAPINTERVALEXTPROC)(void);
typedef BOOL (GLO_API_PTR *PFNWGLGETSYNCVALUESOMLPROC)(HDC hdc, INT64 * ust, INT64 * msc, INT64 * sbc);
typedef BOOL (GLO_API_PTR *PFNWGLGETVIDEODEVICENVPROC)(HDC hDC, int numDevices, HPVIDEODEV * hVideoDevice);
typedef BOOL (GLO_API_PTR *PFNWGLGETVIDEOINFONVPROC)(HPVIDEODEV hpVideoDevice, unsigned long * pulCounterOutputPbuffer, unsigned long * pulCounterOutputVideo);
typedef BOOL (GLO_API_PTR *PFNWGLISENABLEDFRAMELOCKI3DPROC)(BOOL * pFlag);
typedef BOOL (GLO_API_PTR *PFNWGLISENABLEDGENLOCKI3DPROC)(HDC hDC, BOOL * pFlag);
typedef BOOL (GLO_API_PTR *PFNWGLJOINSWAPGROUPNVPROC)(HDC hDC, GLuint group);
typedef GLboolean (GLO_API_PTR *PFNWGLLOADDISPLAYCOLORTABLEEXTPROC)(const GLushort * table, GLuint length);
typedef BOOL (GLO_API_PTR *PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC)(HDC hDc, HVIDEOINPUTDEVICENV hDevice);
typedef BOOL (GLO_API_PTR *PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC)(HGLRC hglrc);
typedef BOOL (GLO_API_PTR *PFNWGLMAKECONTEXTCURRENTARBPROC)(HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
typedef BOOL (GLO_API_PTR *PFNWGLMAKECONTEXTCURRENTEXTPROC)(HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
typedef BOOL (GLO_API_PTR *PFNWGLMAKECURRENTPROC)(HDC hDc, HGLRC newContext);
typedef BOOL (GLO_API_PTR *PFNWGLQUERYCURRENTCONTEXTNVPROC)(int iAttribute, int * piValue);
typedef BOOL (GLO_API_PTR *PFNWGLQUERYFRAMECOUNTNVPROC)(HDC hDC, GLuint * count);
typedef BOOL (GLO_API_PTR *PFNWGLQUERYFRAMELOCKMASTERI3DPROC)(BOOL * pFlag);
typedef BOOL (GLO_API_PTR *PFNWGLQUERYFRAMETRACKINGI3DPROC)(DWORD * pFrameCount, DWORD * pMissedFrames, float * pLastMissedUsage);
typedef BOOL (GLO_API_PTR *PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC)(HDC hDC, UINT * uMaxLineDelay, UINT * uMaxPixelDelay);
typedef BOOL (GLO_API_PTR *PFNWGLQUERYMAXSWAPGROUPSNVPROC)(HDC hDC, GLuint * maxGroups, GLuint * maxBarriers);
typedef BOOL (GLO_API_PTR *PFNWGLQUERYPBUFFERARBPROC)(HPBUFFERARB hPbuffer, int iAttribute, int * piValue);
typedef BOOL (GLO_API_PTR *PFNWGLQUERYPBUFFEREXTPROC)(HPBUFFEREXT hPbuffer, int iAttribute, int * piValue);
typedef BOOL (GLO_API_PTR *PFNWGLQUERYSWAPGROUPNVPROC)(HDC hDC, GLuint * group, GLuint * barrier);
typedef BOOL (GLO_API_PTR *PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC)(HDC hDc, HVIDEOINPUTDEVICENV hDevice, int iAttribute, int * piValue);
typedef BOOL (GLO_API_PTR *PFNWGLREALIZELAYERPALETTEPROC)(HDC hdc, int iLayerPlane, BOOL bRealize);
typedef BOOL (GLO_API_PTR *PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC)(HDC hDC, const LPVOID * pAddress, UINT count);
typedef int (GLO_API_PTR *PFNWGLRELEASEPBUFFERDCARBPROC)(HPBUFFERARB hPbuffer, HDC hDC);
typedef int (GLO_API_PTR *PFNWGLRELEASEPBUFFERDCEXTPROC)(HPBUFFEREXT hPbuffer, HDC hDC);
typedef BOOL (GLO_API_PTR *PFNWGLRELEASETEXIMAGEARBPROC)(HPBUFFERARB hPbuffer, int iBuffer);
typedef BOOL (GLO_API_PTR *PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC)(HDC hDc, HVIDEOINPUTDEVICENV hDevice);
typedef BOOL (GLO_API_PTR *PFNWGLRELEASEVIDEODEVICENVPROC)(HPVIDEODEV hVideoDevice);
typedef BOOL (GLO_API_PTR *PFNWGLRELEASEVIDEOIMAGENVPROC)(HPBUFFERARB hPbuffer, int iVideoBuffer);
typedef BOOL (GLO_API_PTR *PFNWGLRESETFRAMECOUNTNVPROC)(HDC hDC);
typedef BOOL (GLO_API_PTR *PFNWGLRESTOREBUFFERREGIONARBPROC)(HANDLE hRegion, int x, int y, int width, int height, int xSrc, int ySrc);
typedef BOOL (GLO_API_PTR *PFNWGLSAVEBUFFERREGIONARBPROC)(HANDLE hRegion, int x, int y, int width, int height);
typedef BOOL (GLO_API_PTR *PFNWGLSENDPBUFFERTOVIDEONVPROC)(HPBUFFERARB hPbuffer, int iBufferType, unsigned long * pulCounterPbuffer, BOOL bBlock);
typedef BOOL (GLO_API_PTR *PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC)(HDC hDC, int iAttribute, const int * piValue);
typedef BOOL (GLO_API_PTR *PFNWGLSETGAMMATABLEI3DPROC)(HDC hDC, int iEntries, const USHORT * puRed, const USHORT * puGreen, const USHORT * puBlue);
typedef BOOL (GLO_API_PTR *PFNWGLSETGAMMATABLEPARAMETERSI3DPROC)(HDC hDC, int iAttribute, const int * piValue);
typedef int (GLO_API_PTR *PFNWGLSETLAYERPALETTEENTRIESPROC)(HDC hdc, int iLayerPlane, int iStart, int cEntries, const COLORREF * pcr);
typedef BOOL (GLO_API_PTR *PFNWGLSETPBUFFERATTRIBARBPROC)(HPBUFFERARB hPbuffer, const int * piAttribList);
typedef BOOL (GLO_API_PTR *PFNWGLSETSTEREOEMITTERSTATE3DLPROC)(HDC hDC, UINT uState);
typedef BOOL (GLO_API_PTR *PFNWGLSHARELISTSPROC)(HGLRC hrcSrvShare, HGLRC hrcSrvSource);
typedef INT64 (GLO_API_PTR *PFNWGLSWAPBUFFERSMSCOMLPROC)(HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder);
typedef BOOL (GLO_API_PTR *PFNWGLSWAPINTERVALEXTPROC)(int interval);
typedef BOOL (GLO_API_PTR *PFNWGLSWAPLAYERBUFFERSPROC)(HDC hdc, UINT fuFlags);
typedef INT64 (GLO_API_PTR *PFNWGLSWAPLAYERBUFFERSMSCOMLPROC)(HDC hdc, INT fuPlanes, INT64 target_msc, INT64 divisor, INT64 remainder);
typedef BOOL (GLO_API_PTR *PFNWGLUSEFONTBITMAPSPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase);
typedef BOOL (GLO_API_PTR *PFNWGLUSEFONTBITMAPSAPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase);
typedef BOOL (GLO_API_PTR *PFNWGLUSEFONTBITMAPSWPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase);
typedef BOOL (GLO_API_PTR *PFNWGLUSEFONTOUTLINESPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase, FLOAT deviation, FLOAT extrusion, int format, LPGLYPHMETRICSFLOAT lpgmf);
typedef BOOL (GLO_API_PTR *PFNWGLUSEFONTOUTLINESAPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase, FLOAT deviation, FLOAT extrusion, int format, LPGLYPHMETRICSFLOAT lpgmf);
typedef BOOL (GLO_API_PTR *PFNWGLUSEFONTOUTLINESWPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase, FLOAT deviation, FLOAT extrusion, int format, LPGLYPHMETRICSFLOAT lpgmf);
typedef BOOL (GLO_API_PTR *PFNWGLWAITFORMSCOMLPROC)(HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder, INT64 * ust, INT64 * msc, INT64 * sbc);
typedef BOOL (GLO_API_PTR *PFNWGLWAITFORSBCOMLPROC)(HDC hdc, INT64 target_sbc, INT64 * ust, INT64 * msc, INT64 * sbc);

GLO_API_CALL PFNWGLALLOCATEMEMORYNVPROC glo_wglAllocateMemoryNV;
#define wglAllocateMemoryNV glo_wglAllocateMemoryNV
GLO_API_CALL PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC glo_wglAssociateImageBufferEventsI3D;
#define wglAssociateImageBufferEventsI3D glo_wglAssociateImageBufferEventsI3D
GLO_API_CALL PFNWGLBEGINFRAMETRACKINGI3DPROC glo_wglBeginFrameTrackingI3D;
#define wglBeginFrameTrackingI3D glo_wglBeginFrameTrackingI3D
GLO_API_CALL PFNWGLBINDDISPLAYCOLORTABLEEXTPROC glo_wglBindDisplayColorTableEXT;
#define wglBindDisplayColorTableEXT glo_wglBindDisplayColorTableEXT
GLO_API_CALL PFNWGLBINDSWAPBARRIERNVPROC glo_wglBindSwapBarrierNV;
#define wglBindSwapBarrierNV glo_wglBindSwapBarrierNV
GLO_API_CALL PFNWGLBINDTEXIMAGEARBPROC glo_wglBindTexImageARB;
#define wglBindTexImageARB glo_wglBindTexImageARB
GLO_API_CALL PFNWGLBINDVIDEOCAPTUREDEVICENVPROC glo_wglBindVideoCaptureDeviceNV;
#define wglBindVideoCaptureDeviceNV glo_wglBindVideoCaptureDeviceNV
GLO_API_CALL PFNWGLBINDVIDEODEVICENVPROC glo_wglBindVideoDeviceNV;
#define wglBindVideoDeviceNV glo_wglBindVideoDeviceNV
GLO_API_CALL PFNWGLBINDVIDEOIMAGENVPROC glo_wglBindVideoImageNV;
#define wglBindVideoImageNV glo_wglBindVideoImageNV
GLO_API_CALL PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC glo_wglBlitContextFramebufferAMD;
#define wglBlitContextFramebufferAMD glo_wglBlitContextFramebufferAMD
GLO_API_CALL PFNWGLCHOOSEPIXELFORMATARBPROC glo_wglChoosePixelFormatARB;
#define wglChoosePixelFormatARB glo_wglChoosePixelFormatARB
GLO_API_CALL PFNWGLCHOOSEPIXELFORMATEXTPROC glo_wglChoosePixelFormatEXT;
#define wglChoosePixelFormatEXT glo_wglChoosePixelFormatEXT
GLO_API_CALL PFNWGLCOPYIMAGESUBDATANVPROC glo_wglCopyImageSubDataNV;
#define wglCopyImageSubDataNV glo_wglCopyImageSubDataNV
GLO_API_CALL PFNWGLCREATEAFFINITYDCNVPROC glo_wglCreateAffinityDCNV;
#define wglCreateAffinityDCNV glo_wglCreateAffinityDCNV
GLO_API_CALL PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC glo_wglCreateAssociatedContextAMD;
#define wglCreateAssociatedContextAMD glo_wglCreateAssociatedContextAMD
GLO_API_CALL PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC glo_wglCreateAssociatedContextAttribsAMD;
#define wglCreateAssociatedContextAttribsAMD glo_wglCreateAssociatedContextAttribsAMD
GLO_API_CALL PFNWGLCREATEBUFFERREGIONARBPROC glo_wglCreateBufferRegionARB;
#define wglCreateBufferRegionARB glo_wglCreateBufferRegionARB
GLO_API_CALL PFNWGLCREATECONTEXTATTRIBSARBPROC glo_wglCreateContextAttribsARB;
#define wglCreateContextAttribsARB glo_wglCreateContextAttribsARB
GLO_API_CALL PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC glo_wglCreateDisplayColorTableEXT;
#define wglCreateDisplayColorTableEXT glo_wglCreateDisplayColorTableEXT
GLO_API_CALL PFNWGLCREATEIMAGEBUFFERI3DPROC glo_wglCreateImageBufferI3D;
#define wglCreateImageBufferI3D glo_wglCreateImageBufferI3D
GLO_API_CALL PFNWGLCREATEPBUFFERARBPROC glo_wglCreatePbufferARB;
#define wglCreatePbufferARB glo_wglCreatePbufferARB
GLO_API_CALL PFNWGLCREATEPBUFFEREXTPROC glo_wglCreatePbufferEXT;
#define wglCreatePbufferEXT glo_wglCreatePbufferEXT
GLO_API_CALL PFNWGLDXCLOSEDEVICENVPROC glo_wglDXCloseDeviceNV;
#define wglDXCloseDeviceNV glo_wglDXCloseDeviceNV
GLO_API_CALL PFNWGLDXLOCKOBJECTSNVPROC glo_wglDXLockObjectsNV;
#define wglDXLockObjectsNV glo_wglDXLockObjectsNV
GLO_API_CALL PFNWGLDXOBJECTACCESSNVPROC glo_wglDXObjectAccessNV;
#define wglDXObjectAccessNV glo_wglDXObjectAccessNV
GLO_API_CALL PFNWGLDXOPENDEVICENVPROC glo_wglDXOpenDeviceNV;
#define wglDXOpenDeviceNV glo_wglDXOpenDeviceNV
GLO_API_CALL PFNWGLDXREGISTEROBJECTNVPROC glo_wglDXRegisterObjectNV;
#define wglDXRegisterObjectNV glo_wglDXRegisterObjectNV
GLO_API_CALL PFNWGLDXSETRESOURCESHAREHANDLENVPROC glo_wglDXSetResourceShareHandleNV;
#define wglDXSetResourceShareHandleNV glo_wglDXSetResourceShareHandleNV
GLO_API_CALL PFNWGLDXUNLOCKOBJECTSNVPROC glo_wglDXUnlockObjectsNV;
#define wglDXUnlockObjectsNV glo_wglDXUnlockObjectsNV
GLO_API_CALL PFNWGLDXUNREGISTEROBJECTNVPROC glo_wglDXUnregisterObjectNV;
#define wglDXUnregisterObjectNV glo_wglDXUnregisterObjectNV
GLO_API_CALL PFNWGLDELAYBEFORESWAPNVPROC glo_wglDelayBeforeSwapNV;
#define wglDelayBeforeSwapNV glo_wglDelayBeforeSwapNV
GLO_API_CALL PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC glo_wglDeleteAssociatedContextAMD;
#define wglDeleteAssociatedContextAMD glo_wglDeleteAssociatedContextAMD
GLO_API_CALL PFNWGLDELETEBUFFERREGIONARBPROC glo_wglDeleteBufferRegionARB;
#define wglDeleteBufferRegionARB glo_wglDeleteBufferRegionARB
GLO_API_CALL PFNWGLDELETEDCNVPROC glo_wglDeleteDCNV;
#define wglDeleteDCNV glo_wglDeleteDCNV
GLO_API_CALL PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC glo_wglDestroyDisplayColorTableEXT;
#define wglDestroyDisplayColorTableEXT glo_wglDestroyDisplayColorTableEXT
GLO_API_CALL PFNWGLDESTROYIMAGEBUFFERI3DPROC glo_wglDestroyImageBufferI3D;
#define wglDestroyImageBufferI3D glo_wglDestroyImageBufferI3D
GLO_API_CALL PFNWGLDESTROYPBUFFERARBPROC glo_wglDestroyPbufferARB;
#define wglDestroyPbufferARB glo_wglDestroyPbufferARB
GLO_API_CALL PFNWGLDESTROYPBUFFEREXTPROC glo_wglDestroyPbufferEXT;
#define wglDestroyPbufferEXT glo_wglDestroyPbufferEXT
GLO_API_CALL PFNWGLDISABLEFRAMELOCKI3DPROC glo_wglDisableFrameLockI3D;
#define wglDisableFrameLockI3D glo_wglDisableFrameLockI3D
GLO_API_CALL PFNWGLDISABLEGENLOCKI3DPROC glo_wglDisableGenlockI3D;
#define wglDisableGenlockI3D glo_wglDisableGenlockI3D
GLO_API_CALL PFNWGLENABLEFRAMELOCKI3DPROC glo_wglEnableFrameLockI3D;
#define wglEnableFrameLockI3D glo_wglEnableFrameLockI3D
GLO_API_CALL PFNWGLENABLEGENLOCKI3DPROC glo_wglEnableGenlockI3D;
#define wglEnableGenlockI3D glo_wglEnableGenlockI3D
GLO_API_CALL PFNWGLENDFRAMETRACKINGI3DPROC glo_wglEndFrameTrackingI3D;
#define wglEndFrameTrackingI3D glo_wglEndFrameTrackingI3D
GLO_API_CALL PFNWGLENUMGPUDEVICESNVPROC glo_wglEnumGpuDevicesNV;
#define wglEnumGpuDevicesNV glo_wglEnumGpuDevicesNV
GLO_API_CALL PFNWGLENUMGPUSFROMAFFINITYDCNVPROC glo_wglEnumGpusFromAffinityDCNV;
#define wglEnumGpusFromAffinityDCNV glo_wglEnumGpusFromAffinityDCNV
GLO_API_CALL PFNWGLENUMGPUSNVPROC glo_wglEnumGpusNV;
#define wglEnumGpusNV glo_wglEnumGpusNV
GLO_API_CALL PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC glo_wglEnumerateVideoCaptureDevicesNV;
#define wglEnumerateVideoCaptureDevicesNV glo_wglEnumerateVideoCaptureDevicesNV
GLO_API_CALL PFNWGLENUMERATEVIDEODEVICESNVPROC glo_wglEnumerateVideoDevicesNV;
#define wglEnumerateVideoDevicesNV glo_wglEnumerateVideoDevicesNV
GLO_API_CALL PFNWGLFREEMEMORYNVPROC glo_wglFreeMemoryNV;
#define wglFreeMemoryNV glo_wglFreeMemoryNV
GLO_API_CALL PFNWGLGENLOCKSAMPLERATEI3DPROC glo_wglGenlockSampleRateI3D;
#define wglGenlockSampleRateI3D glo_wglGenlockSampleRateI3D
GLO_API_CALL PFNWGLGENLOCKSOURCEDELAYI3DPROC glo_wglGenlockSourceDelayI3D;
#define wglGenlockSourceDelayI3D glo_wglGenlockSourceDelayI3D
GLO_API_CALL PFNWGLGENLOCKSOURCEEDGEI3DPROC glo_wglGenlockSourceEdgeI3D;
#define wglGenlockSourceEdgeI3D glo_wglGenlockSourceEdgeI3D
GLO_API_CALL PFNWGLGENLOCKSOURCEI3DPROC glo_wglGenlockSourceI3D;
#define wglGenlockSourceI3D glo_wglGenlockSourceI3D
GLO_API_CALL PFNWGLGETCONTEXTGPUIDAMDPROC glo_wglGetContextGPUIDAMD;
#define wglGetContextGPUIDAMD glo_wglGetContextGPUIDAMD
GLO_API_CALL PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC glo_wglGetCurrentAssociatedContextAMD;
#define wglGetCurrentAssociatedContextAMD glo_wglGetCurrentAssociatedContextAMD
GLO_API_CALL PFNWGLGETCURRENTREADDCARBPROC glo_wglGetCurrentReadDCARB;
#define wglGetCurrentReadDCARB glo_wglGetCurrentReadDCARB
GLO_API_CALL PFNWGLGETCURRENTREADDCEXTPROC glo_wglGetCurrentReadDCEXT;
#define wglGetCurrentReadDCEXT glo_wglGetCurrentReadDCEXT
GLO_API_CALL PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC glo_wglGetDigitalVideoParametersI3D;
#define wglGetDigitalVideoParametersI3D glo_wglGetDigitalVideoParametersI3D
GLO_API_CALL PFNWGLGETEXTENSIONSSTRINGARBPROC glo_wglGetExtensionsStringARB;
#define wglGetExtensionsStringARB glo_wglGetExtensionsStringARB
GLO_API_CALL PFNWGLGETEXTENSIONSSTRINGEXTPROC glo_wglGetExtensionsStringEXT;
#define wglGetExtensionsStringEXT glo_wglGetExtensionsStringEXT
GLO_API_CALL PFNWGLGETFRAMEUSAGEI3DPROC glo_wglGetFrameUsageI3D;
#define wglGetFrameUsageI3D glo_wglGetFrameUsageI3D
GLO_API_CALL PFNWGLGETGPUIDSAMDPROC glo_wglGetGPUIDsAMD;
#define wglGetGPUIDsAMD glo_wglGetGPUIDsAMD
GLO_API_CALL PFNWGLGETGPUINFOAMDPROC glo_wglGetGPUInfoAMD;
#define wglGetGPUInfoAMD glo_wglGetGPUInfoAMD
GLO_API_CALL PFNWGLGETGAMMATABLEI3DPROC glo_wglGetGammaTableI3D;
#define wglGetGammaTableI3D glo_wglGetGammaTableI3D
GLO_API_CALL PFNWGLGETGAMMATABLEPARAMETERSI3DPROC glo_wglGetGammaTableParametersI3D;
#define wglGetGammaTableParametersI3D glo_wglGetGammaTableParametersI3D
GLO_API_CALL PFNWGLGETGENLOCKSAMPLERATEI3DPROC glo_wglGetGenlockSampleRateI3D;
#define wglGetGenlockSampleRateI3D glo_wglGetGenlockSampleRateI3D
GLO_API_CALL PFNWGLGETGENLOCKSOURCEDELAYI3DPROC glo_wglGetGenlockSourceDelayI3D;
#define wglGetGenlockSourceDelayI3D glo_wglGetGenlockSourceDelayI3D
GLO_API_CALL PFNWGLGETGENLOCKSOURCEEDGEI3DPROC glo_wglGetGenlockSourceEdgeI3D;
#define wglGetGenlockSourceEdgeI3D glo_wglGetGenlockSourceEdgeI3D
GLO_API_CALL PFNWGLGETGENLOCKSOURCEI3DPROC glo_wglGetGenlockSourceI3D;
#define wglGetGenlockSourceI3D glo_wglGetGenlockSourceI3D
GLO_API_CALL PFNWGLGETMSCRATEOMLPROC glo_wglGetMscRateOML;
#define wglGetMscRateOML glo_wglGetMscRateOML
GLO_API_CALL PFNWGLGETPBUFFERDCARBPROC glo_wglGetPbufferDCARB;
#define wglGetPbufferDCARB glo_wglGetPbufferDCARB
GLO_API_CALL PFNWGLGETPBUFFERDCEXTPROC glo_wglGetPbufferDCEXT;
#define wglGetPbufferDCEXT glo_wglGetPbufferDCEXT
GLO_API_CALL PFNWGLGETPIXELFORMATATTRIBFVARBPROC glo_wglGetPixelFormatAttribfvARB;
#define wglGetPixelFormatAttribfvARB glo_wglGetPixelFormatAttribfvARB
GLO_API_CALL PFNWGLGETPIXELFORMATATTRIBFVEXTPROC glo_wglGetPixelFormatAttribfvEXT;
#define wglGetPixelFormatAttribfvEXT glo_wglGetPixelFormatAttribfvEXT
GLO_API_CALL PFNWGLGETPIXELFORMATATTRIBIVARBPROC glo_wglGetPixelFormatAttribivARB;
#define wglGetPixelFormatAttribivARB glo_wglGetPixelFormatAttribivARB
GLO_API_CALL PFNWGLGETPIXELFORMATATTRIBIVEXTPROC glo_wglGetPixelFormatAttribivEXT;
#define wglGetPixelFormatAttribivEXT glo_wglGetPixelFormatAttribivEXT
GLO_API_CALL PFNWGLGETSWAPINTERVALEXTPROC glo_wglGetSwapIntervalEXT;
#define wglGetSwapIntervalEXT glo_wglGetSwapIntervalEXT
GLO_API_CALL PFNWGLGETSYNCVALUESOMLPROC glo_wglGetSyncValuesOML;
#define wglGetSyncValuesOML glo_wglGetSyncValuesOML
GLO_API_CALL PFNWGLGETVIDEODEVICENVPROC glo_wglGetVideoDeviceNV;
#define wglGetVideoDeviceNV glo_wglGetVideoDeviceNV
GLO_API_CALL PFNWGLGETVIDEOINFONVPROC glo_wglGetVideoInfoNV;
#define wglGetVideoInfoNV glo_wglGetVideoInfoNV
GLO_API_CALL PFNWGLISENABLEDFRAMELOCKI3DPROC glo_wglIsEnabledFrameLockI3D;
#define wglIsEnabledFrameLockI3D glo_wglIsEnabledFrameLockI3D
GLO_API_CALL PFNWGLISENABLEDGENLOCKI3DPROC glo_wglIsEnabledGenlockI3D;
#define wglIsEnabledGenlockI3D glo_wglIsEnabledGenlockI3D
GLO_API_CALL PFNWGLJOINSWAPGROUPNVPROC glo_wglJoinSwapGroupNV;
#define wglJoinSwapGroupNV glo_wglJoinSwapGroupNV
GLO_API_CALL PFNWGLLOADDISPLAYCOLORTABLEEXTPROC glo_wglLoadDisplayColorTableEXT;
#define wglLoadDisplayColorTableEXT glo_wglLoadDisplayColorTableEXT
GLO_API_CALL PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC glo_wglLockVideoCaptureDeviceNV;
#define wglLockVideoCaptureDeviceNV glo_wglLockVideoCaptureDeviceNV
GLO_API_CALL PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC glo_wglMakeAssociatedContextCurrentAMD;
#define wglMakeAssociatedContextCurrentAMD glo_wglMakeAssociatedContextCurrentAMD
GLO_API_CALL PFNWGLMAKECONTEXTCURRENTARBPROC glo_wglMakeContextCurrentARB;
#define wglMakeContextCurrentARB glo_wglMakeContextCurrentARB
GLO_API_CALL PFNWGLMAKECONTEXTCURRENTEXTPROC glo_wglMakeContextCurrentEXT;
#define wglMakeContextCurrentEXT glo_wglMakeContextCurrentEXT
GLO_API_CALL PFNWGLQUERYCURRENTCONTEXTNVPROC glo_wglQueryCurrentContextNV;
#define wglQueryCurrentContextNV glo_wglQueryCurrentContextNV
GLO_API_CALL PFNWGLQUERYFRAMECOUNTNVPROC glo_wglQueryFrameCountNV;
#define wglQueryFrameCountNV glo_wglQueryFrameCountNV
GLO_API_CALL PFNWGLQUERYFRAMELOCKMASTERI3DPROC glo_wglQueryFrameLockMasterI3D;
#define wglQueryFrameLockMasterI3D glo_wglQueryFrameLockMasterI3D
GLO_API_CALL PFNWGLQUERYFRAMETRACKINGI3DPROC glo_wglQueryFrameTrackingI3D;
#define wglQueryFrameTrackingI3D glo_wglQueryFrameTrackingI3D
GLO_API_CALL PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC glo_wglQueryGenlockMaxSourceDelayI3D;
#define wglQueryGenlockMaxSourceDelayI3D glo_wglQueryGenlockMaxSourceDelayI3D
GLO_API_CALL PFNWGLQUERYMAXSWAPGROUPSNVPROC glo_wglQueryMaxSwapGroupsNV;
#define wglQueryMaxSwapGroupsNV glo_wglQueryMaxSwapGroupsNV
GLO_API_CALL PFNWGLQUERYPBUFFERARBPROC glo_wglQueryPbufferARB;
#define wglQueryPbufferARB glo_wglQueryPbufferARB
GLO_API_CALL PFNWGLQUERYPBUFFEREXTPROC glo_wglQueryPbufferEXT;
#define wglQueryPbufferEXT glo_wglQueryPbufferEXT
GLO_API_CALL PFNWGLQUERYSWAPGROUPNVPROC glo_wglQuerySwapGroupNV;
#define wglQuerySwapGroupNV glo_wglQuerySwapGroupNV
GLO_API_CALL PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC glo_wglQueryVideoCaptureDeviceNV;
#define wglQueryVideoCaptureDeviceNV glo_wglQueryVideoCaptureDeviceNV
GLO_API_CALL PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC glo_wglReleaseImageBufferEventsI3D;
#define wglReleaseImageBufferEventsI3D glo_wglReleaseImageBufferEventsI3D
GLO_API_CALL PFNWGLRELEASEPBUFFERDCARBPROC glo_wglReleasePbufferDCARB;
#define wglReleasePbufferDCARB glo_wglReleasePbufferDCARB
GLO_API_CALL PFNWGLRELEASEPBUFFERDCEXTPROC glo_wglReleasePbufferDCEXT;
#define wglReleasePbufferDCEXT glo_wglReleasePbufferDCEXT
GLO_API_CALL PFNWGLRELEASETEXIMAGEARBPROC glo_wglReleaseTexImageARB;
#define wglReleaseTexImageARB glo_wglReleaseTexImageARB
GLO_API_CALL PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC glo_wglReleaseVideoCaptureDeviceNV;
#define wglReleaseVideoCaptureDeviceNV glo_wglReleaseVideoCaptureDeviceNV
GLO_API_CALL PFNWGLRELEASEVIDEODEVICENVPROC glo_wglReleaseVideoDeviceNV;
#define wglReleaseVideoDeviceNV glo_wglReleaseVideoDeviceNV
GLO_API_CALL PFNWGLRELEASEVIDEOIMAGENVPROC glo_wglReleaseVideoImageNV;
#define wglReleaseVideoImageNV glo_wglReleaseVideoImageNV
GLO_API_CALL PFNWGLRESETFRAMECOUNTNVPROC glo_wglResetFrameCountNV;
#define wglResetFrameCountNV glo_wglResetFrameCountNV
GLO_API_CALL PFNWGLRESTOREBUFFERREGIONARBPROC glo_wglRestoreBufferRegionARB;
#define wglRestoreBufferRegionARB glo_wglRestoreBufferRegionARB
GLO_API_CALL PFNWGLSAVEBUFFERREGIONARBPROC glo_wglSaveBufferRegionARB;
#define wglSaveBufferRegionARB glo_wglSaveBufferRegionARB
GLO_API_CALL PFNWGLSENDPBUFFERTOVIDEONVPROC glo_wglSendPbufferToVideoNV;
#define wglSendPbufferToVideoNV glo_wglSendPbufferToVideoNV
GLO_API_CALL PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC glo_wglSetDigitalVideoParametersI3D;
#define wglSetDigitalVideoParametersI3D glo_wglSetDigitalVideoParametersI3D
GLO_API_CALL PFNWGLSETGAMMATABLEI3DPROC glo_wglSetGammaTableI3D;
#define wglSetGammaTableI3D glo_wglSetGammaTableI3D
GLO_API_CALL PFNWGLSETGAMMATABLEPARAMETERSI3DPROC glo_wglSetGammaTableParametersI3D;
#define wglSetGammaTableParametersI3D glo_wglSetGammaTableParametersI3D
GLO_API_CALL PFNWGLSETPBUFFERATTRIBARBPROC glo_wglSetPbufferAttribARB;
#define wglSetPbufferAttribARB glo_wglSetPbufferAttribARB
GLO_API_CALL PFNWGLSETSTEREOEMITTERSTATE3DLPROC glo_wglSetStereoEmitterState3DL;
#define wglSetStereoEmitterState3DL glo_wglSetStereoEmitterState3DL
GLO_API_CALL PFNWGLSWAPBUFFERSMSCOMLPROC glo_wglSwapBuffersMscOML;
#define wglSwapBuffersMscOML glo_wglSwapBuffersMscOML
GLO_API_CALL PFNWGLSWAPINTERVALEXTPROC glo_wglSwapIntervalEXT;
#define wglSwapIntervalEXT glo_wglSwapIntervalEXT
GLO_API_CALL PFNWGLSWAPLAYERBUFFERSMSCOMLPROC glo_wglSwapLayerBuffersMscOML;
#define wglSwapLayerBuffersMscOML glo_wglSwapLayerBuffersMscOML
GLO_API_CALL PFNWGLWAITFORMSCOMLPROC glo_wglWaitForMscOML;
#define wglWaitForMscOML glo_wglWaitForMscOML
GLO_API_CALL PFNWGLWAITFORSBCOMLPROC glo_wglWaitForSbcOML;
#define wglWaitForSbcOML glo_wglWaitForSbcOML





GLO_API_CALL int gloLoadWGLUserPtr(HDC hdc, GLOuserptrloadfunc load, void *userptr);
GLO_API_CALL int gloLoadWGL(HDC hdc, GLOloadfunc load);

#ifdef GLO_WGL

GLO_API_CALL int gloLoaderLoadWGL(HDC hdc);

#endif
#ifdef __cplusplus
}
#endif

#endif

#endif
